#!/usr/bin/env python3
"""Part 3: Sections 5 (headings+callouts), 6, 7, 8 remaining"""
import json

with open('/home/user/oracletrading/ayilon/bot-guide.html', 'r', encoding='utf-8') as f:
    content = f.read()

html_attrs = [
    # S05
    ('  <p>AYILON supports 10 trading strategies.', '  <p data-guide-i18n="s05.p1">AYILON supports 10 trading strategies.'),
    ('  <h3>Strategy 1 — RSI Oversold DCA Long</h3>', '  <h3 data-guide-i18n="s05.h1">Strategy 1 — RSI Oversold DCA Long</h3>'),
    ('  <h3>Strategy 2 — MA Support DCA</h3>', '  <h3 data-guide-i18n="s05.h2">Strategy 2 — MA Support DCA</h3>'),
    ('  <h3>Strategy 3 — S/R Bounce (Default)</h3>', '  <h3 data-guide-i18n="s05.h3">Strategy 3 — S/R Bounce (Default)</h3>'),
    ('  <div class="callout">\n    <div class="callout-label">Entry Conditions — All 3 Required</div>', '  <div class="callout" data-guide-i18n="s05.callout1">\n    <div class="callout-label">Entry Conditions — All 3 Required</div>'),
    ('  <h3>Strategy 4 — MA Crossover + RSI Confirmation</h3>', '  <h3 data-guide-i18n="s05.h4">Strategy 4 — MA Crossover + RSI Confirmation</h3>'),
    ('  <h3>Strategy 5 — Bollinger Band Mean Reversion</h3>', '  <h3 data-guide-i18n="s05.h5">Strategy 5 — Bollinger Band Mean Reversion</h3>'),
    ('  <h3>Strategy 6 — Breakout + Volume Confirmation</h3>', '  <h3 data-guide-i18n="s05.h6">Strategy 6 — Breakout + Volume Confirmation</h3>'),
    ('  <h3>Strategy 7 — MA Ribbon Long</h3>', '  <h3 data-guide-i18n="s05.h7">Strategy 7 — MA Ribbon Long</h3>'),
    ('  <h3>Strategy 8 — MACD Divergence</h3>', '  <h3 data-guide-i18n="s05.h8">Strategy 8 — MACD Divergence</h3>'),
    ('  <div class="callout yellow">\n    <div class="callout-label">High Risk</div>\n    Divergence can persist', '  <div class="callout yellow" data-guide-i18n="s05.callout2">\n    <div class="callout-label">High Risk</div>\n    Divergence can persist'),
    ('  <h3>Strategy 9 — Funding Rate Contrarian</h3>', '  <h3 data-guide-i18n="s05.h9">Strategy 9 — Funding Rate Contrarian</h3>'),
    ('  <div class="callout yellow">\n    <div class="callout-label">High Risk</div>\n    Funding rates alone', '  <div class="callout yellow" data-guide-i18n="s05.callout3">\n    <div class="callout-label">High Risk</div>\n    Funding rates alone'),
    ('  <h3>Strategy 10 — ATR Trend Following</h3>', '  <h3 data-guide-i18n="s05.h10">Strategy 10 — ATR Trend Following</h3>'),
    # S06
    ('  <p>AYILON uses a <strong>Fixed Fractional</strong> position sizing model.', '  <p data-guide-i18n="s06.p1">AYILON uses a <strong>Fixed Fractional</strong> position sizing model.'),
    ('      <div class="card-desc">Default. Amount of equity you are willing to lose', '      <div class="card-desc" data-guide-i18n="s06.card1">Default. Amount of equity you are willing to lose'),
    ('      <div class="card-desc">Bot pauses for the day once cumulative realized', '      <div class="card-desc" data-guide-i18n="s06.card2">Bot pauses for the day once cumulative realized'),
    ('      <div class="card-desc">User-configured. Each entry is equally spaced', '      <div class="card-desc" data-guide-i18n="s06.card3">User-configured. Each entry is equally spaced'),
    ('  <h3>DCA Entry Spacing — N-Equal-Parts</h3>', '  <h3 data-guide-i18n="s06.h1">DCA Entry Spacing — N-Equal-Parts</h3>'),
    ('  <p>Instead of a fixed price interval between DCA entries,', '  <p data-guide-i18n="s06.p2">Instead of a fixed price interval between DCA entries,'),
    ('  <p><strong>Example (Long, 3 entries):</strong>', '  <p data-guide-i18n="s06.p3"><strong>Example (Long, 3 entries):</strong>'),
    ('  <h3>Entry Sizing Modes</h3>', '  <h3 data-guide-i18n="s06.h2">Entry Sizing Modes</h3>'),
    ('  <div class="callout yellow">\n    <div class="callout-label">Martingale Warning</div>', '  <div class="callout yellow" data-guide-i18n="s06.callout1">\n    <div class="callout-label">Martingale Warning</div>'),
    ('  <div class="callout">\n    <div class="callout-label">Risk Cap</div>', '  <div class="callout" data-guide-i18n="s06.callout2">\n    <div class="callout-label">Risk Cap</div>'),
    # S07
    ('  <h3>Rule 1 — No Direction Flip</h3>', '  <h3 data-guide-i18n="s07.h1">Rule 1 — No Direction Flip</h3>'),
    ('  <p>If the bot already holds an open position', '  <p data-guide-i18n="s07.p1">If the bot already holds an open position'),
    ('  <h3>Rule 2 — Maximum Entry Count</h3>', '  <h3 data-guide-i18n="s07.h2">Rule 2 — Maximum Entry Count</h3>'),
    ('  <p>The bot tracks how many entries have been placed', '  <p data-guide-i18n="s07.p2">The bot tracks how many entries have been placed'),
    ('  <h3>Rule 3 — DCA Zone Containment</h3>', '  <h3 data-guide-i18n="s07.h3">Rule 3 — DCA Zone Containment</h3>'),
    ('  <p>All DCA entries are pre-calculated at signal time', '  <p data-guide-i18n="s07.p3">All DCA entries are pre-calculated at signal time'),
    ('  <div class="callout red">\n    <div class="callout-label">Why This Matters</div>', '  <div class="callout red" data-guide-i18n="s07.callout1">\n    <div class="callout-label">Why This Matters</div>'),
    # S08 remaining
    ('  <h3>TP Level Selection</h3>', '  <h3 data-guide-i18n="s08.h1">TP Level Selection</h3>'),
    ('  <h3>What Happens on TP Hit</h3>', '  <h3 data-guide-i18n="s08.h2">What Happens on TP Hit</h3>'),
    ('        <div class="flow-name">Close half the position size (반 익절)</div>', '        <div class="flow-name" data-guide-i18n="s08.f1.name">Close half the position size</div>'),
    ('        <div class="flow-desc">Bot places a market order to close exactly <strong>half the total size held</strong>', '        <div class="flow-desc" data-guide-i18n="s08.f1.desc">Bot places a market order to close exactly <strong>half the total size held</strong>'),
    ('        <div class="flow-name">SL Moves to Average Entry (본절)</div>', '        <div class="flow-name" data-guide-i18n="s08.f2.name">SL Moves to Average Entry (Break-Even)</div>'),
    ('        <div class="flow-desc">Stop loss is moved to the weighted average entry price', '        <div class="flow-desc" data-guide-i18n="s08.f2.desc">Stop loss is moved to the weighted average entry price'),
    ('        <div class="flow-name">Remaining Half Rides Free</div>', '        <div class="flow-name" data-guide-i18n="s08.f3.name">Remaining Half Rides Free</div>'),
    ('        <div class="flow-desc">No fixed TP for the second half.', '        <div class="flow-desc" data-guide-i18n="s08.f3.desc">No fixed TP for the second half.'),
    ('  <div class="callout green">\n    <div class="callout-label">The Logic</div>', '  <div class="callout green" data-guide-i18n="s08.callout2">\n    <div class="callout-label">The Logic</div>'),
    # S11
    ('  <p>Walk-through of a complete LONG trade on BTC-USDT-SWAP', '  <p data-guide-i18n="s11.p1">Walk-through of a complete LONG trade on BTC-USDT-SWAP'),
]

for old, new in html_attrs:
    assert old in content, f"NOT FOUND: {repr(old[:70])}"
    content = content.replace(old, new, 1)

print(f"Added {len(html_attrs)} attrs")

# ── Translations ──────────────────────────────────────────────────────────────
patch = {lang: {} for lang in ['ko','ja','zh','vi','ru','tr','es','pt','id']}

# Helper
def add(lang_dict):
    for lang, vals in lang_dict.items():
        patch[lang].update(vals)

# S05 translations
add({
'ko': {
    's05.p1': 'AYILON은 10가지 매매 전략을 지원합니다. 구독 플랜에 따라 사용 가능한 전략이 결정됩니다. 모든 전략은 섹션 06–13에 설명된 동일한 DCA 진입 로직, 포지션 크기, 리스크 관리 프레임워크를 공유합니다.',
    's05.h1': '전략 1 — RSI 과매도 DCA 롱',
    's05.h2': '전략 2 — MA 지지 DCA',
    's05.h3': '전략 3 — S/R 바운스 (기본값)',
    's05.callout1': '<div class="callout-label">진입 조건 — 3가지 모두 필요</div><strong>①</strong> 가격이 S/R 레벨의 ±0.4% 이내 &nbsp;|&nbsp; <strong>②</strong> 모멘텀 방향이 확인됨 (롱은 바운스, 숏은 거절) &nbsp;|&nbsp; <strong>③</strong> SL 거리가 진입가에서 1–7% (노이즈 및 과도하게 넓은 스탑 필터링)',
    's05.h4': '전략 4 — MA 크로스오버 + RSI 확인',
    's05.h5': '전략 5 — 볼린저 밴드 평균 회귀',
    's05.h6': '전략 6 — 브레이크아웃 + 거래량 확인',
    's05.h7': '전략 7 — MA 리본 롱',
    's05.h8': '전략 8 — MACD 다이버전스',
    's05.callout2': '<div class="callout-label">고위험</div>다이버전스는 해소되기 전에 많은 캔들 동안 지속될 수 있습니다. 이 전략에는 보수적인 DCA 수(2–3 진입)와 작은 포지션 크기를 사용하세요.',
    's05.h9': '전략 9 — 펀딩 레이트 역방향',
    's05.callout3': '<div class="callout-label">고위험</div>펀딩 레이트만으로는 방향을 결정할 수 없습니다. 추세 시장에서는 극단적인 펀딩이 며칠 동안 지속될 수 있습니다. 추세 필터와 함께 사용하거나 작은 포지션 크기를 활용하세요.',
    's05.h10': '전략 10 — ATR 추세 추종',
},
'ja': {
    's05.p1': 'AYILONは10の取引戦略をサポートします。サブスクリプションプランによって利用可能な戦略が決まります。すべての戦略はセクション06–13で説明されている同じDCAエントリーロジック、ポジションサイジング、リスク管理フレームワークを共有します。',
    's05.h1': '戦略1 — RSI売られすぎDCAロング',
    's05.h2': '戦略2 — MAサポートDCA',
    's05.h3': '戦略3 — S/Rバウンス（デフォルト）',
    's05.callout1': '<div class="callout-label">エントリー条件 — 3つすべて必須</div><strong>①</strong> 価格がS/Rレベルの±0.4%以内 &nbsp;|&nbsp; <strong>②</strong> モメンタムの方向が確認（ロングはバウンス、ショートはリジェクション） &nbsp;|&nbsp; <strong>③</strong> SL距離がエントリーから1〜7%（ノイズと過度に広いストップをフィルタリング）',
    's05.h4': '戦略4 — MAクロスオーバー + RSI確認',
    's05.h5': '戦略5 — ボリンジャーバンド平均回帰',
    's05.h6': '戦略6 — ブレイクアウト + 出来高確認',
    's05.h7': '戦略7 — MAリボンロング',
    's05.h8': '戦略8 — MACDダイバージェンス',
    's05.callout2': '<div class="callout-label">高リスク</div>ダイバージェンスは解消される前に多くのローソク足にわたって継続することがあります。この戦略では保守的なDCA数（2〜3エントリー）と小さいポジションサイズを使用してください。',
    's05.h9': '戦略9 — ファンディングレート逆張り',
    's05.callout3': '<div class="callout-label">高リスク</div>ファンディングレートだけでは方向を決定できません。トレンド市場では極端なファンディングが数日間続くことがあります。トレンドフィルターと組み合わせるか、小さいポジションサイズを使用してください。',
    's05.h10': '戦略10 — ATRトレンドフォロー',
},
'zh': {
    's05.p1': 'AYILON支持10种交易策略。您的订阅计划决定哪些策略可用。所有策略共享第06–13节中描述的相同DCA入场逻辑、仓位管理和风险管理框架。',
    's05.h1': '策略1 — RSI超卖DCA做多',
    's05.h2': '策略2 — MA支撑DCA',
    's05.h3': '策略3 — S/R反弹（默认）',
    's05.callout1': '<div class="callout-label">入场条件 — 三项全部满足</div><strong>①</strong> 价格在S/R级别的±0.4%以内 &nbsp;|&nbsp; <strong>②</strong> 动能方向确认（做多为反弹，做空为拒绝） &nbsp;|&nbsp; <strong>③</strong> SL距离为入场价的1–7%（过滤噪音和过宽止损）',
    's05.h4': '策略4 — MA交叉 + RSI确认',
    's05.h5': '策略5 — 布林带均值回归',
    's05.h6': '策略6 — 突破 + 成交量确认',
    's05.h7': '策略7 — MA带状做多',
    's05.h8': '策略8 — MACD背离',
    's05.callout2': '<div class="callout-label">高风险</div>背离在解除前可能持续很多根K线。使用此策略时，请采用保守的DCA数量（2–3次入场）和较小的仓位。',
    's05.h9': '策略9 — 资金费率逆向',
    's05.callout3': '<div class="callout-label">高风险</div>仅凭资金费率无法确定方向。在趋势市场中，极端资金费率可能持续数天。结合趋势过滤器使用或采用小仓位。',
    's05.h10': '策略10 — ATR趋势跟随',
},
'vi': {
    's05.p1': 'AYILON hỗ trợ 10 chiến lược giao dịch. Gói đăng ký của bạn xác định những chiến lược nào có thể sử dụng. Tất cả chiến lược chia sẻ cùng logic vào lệnh DCA, quản lý kích cỡ vị thế và khung quản lý rủi ro được mô tả trong các mục 06–13.',
    's05.h1': 'Chiến lược 1 — RSI quá bán DCA Long',
    's05.h2': 'Chiến lược 2 — MA hỗ trợ DCA',
    's05.h3': 'Chiến lược 3 — S/R Bounce (Mặc định)',
    's05.callout1': '<div class="callout-label">Điều kiện vào lệnh — Cần đủ cả 3</div><strong>①</strong> Giá trong phạm vi ±0.4% của mức S/R &nbsp;|&nbsp; <strong>②</strong> Động lượng xác nhận hướng (bounce cho long, rejection cho short) &nbsp;|&nbsp; <strong>③</strong> Khoảng cách SL 1–7% từ vào lệnh (lọc nhiễu và stop quá rộng)',
    's05.h4': 'Chiến lược 4 — MA Crossover + Xác nhận RSI',
    's05.h5': 'Chiến lược 5 — Bollinger Band Mean Reversion',
    's05.h6': 'Chiến lược 6 — Breakout + Xác nhận khối lượng',
    's05.h7': 'Chiến lược 7 — MA Ribbon Long',
    's05.h8': 'Chiến lược 8 — MACD Divergence',
    's05.callout2': '<div class="callout-label">Rủi ro cao</div>Divergence có thể kéo dài nhiều nến trước khi giải quyết. Sử dụng số DCA bảo thủ (2–3 lần vào) và kích cỡ vị thế nhỏ hơn với chiến lược này.',
    's05.h9': 'Chiến lược 9 — Funding Rate Contrarian',
    's05.callout3': '<div class="callout-label">Rủi ro cao</div>Funding rate một mình không xác định được hướng. Funding cực đoan có thể tiếp tục nhiều ngày trong thị trường có xu hướng. Kết hợp với bộ lọc xu hướng hoặc sử dụng vị thế nhỏ.',
    's05.h10': 'Chiến lược 10 — ATR Trend Following',
},
'ru': {
    's05.p1': 'AYILON поддерживает 10 торговых стратегий. Ваш тарифный план определяет, какие из них доступны. Все стратегии используют одну логику входа DCA, управление позицией и риск-менеджмент, описанные в разделах 06–13.',
    's05.h1': 'Стратегия 1 — DCA лонг на перепроданности RSI',
    's05.h2': 'Стратегия 2 — DCA от уровня MA',
    's05.h3': 'Стратегия 3 — Отскок от S/R (по умолчанию)',
    's05.callout1': '<div class="callout-label">Условия входа — Все 3 обязательны</div><strong>①</strong> Цена в пределах ±0.4% от уровня S/R &nbsp;|&nbsp; <strong>②</strong> Моментум подтверждает направление (отскок для лонга, отклонение для шорта) &nbsp;|&nbsp; <strong>③</strong> Расстояние SL 1–7% от входа (фильтр шума и слишком широких стопов)',
    's05.h4': 'Стратегия 4 — Пересечение MA + подтверждение RSI',
    's05.h5': 'Стратегия 5 — Возврат к среднему по Боллинджеру',
    's05.h6': 'Стратегия 6 — Пробой + подтверждение объёмом',
    's05.h7': 'Стратегия 7 — Лонг по ленте MA',
    's05.h8': 'Стратегия 8 — Дивергенция MACD',
    's05.callout2': '<div class="callout-label">Высокий риск</div>Дивергенция может сохраняться много свечей до разрешения. Используйте консервативное число DCA (2–3 входа) и меньшие размеры позиций с этой стратегией.',
    's05.h9': 'Стратегия 9 — Контрарная по ставке финансирования',
    's05.callout3': '<div class="callout-label">Высокий риск</div>Ставка финансирования сама по себе не определяет направление. В трендовых рынках экстремальное финансирование может продолжаться несколько дней. Комбинируйте с трендовым фильтром или используйте небольшие позиции.',
    's05.h10': 'Стратегия 10 — Следование тренду по ATR',
},
'tr': {
    's05.p1': 'AYILON 10 işlem stratejisini destekler. Abonelik planınız hangilerinin kullanılabilir olduğunu belirler. Tüm stratejiler bölüm 06–13\'te açıklanan aynı DCA giriş mantığını, pozisyon büyüklüğünü ve risk yönetimi çerçevesini paylaşır.',
    's05.h1': 'Strateji 1 — RSI Aşırı Satım DCA Long',
    's05.h2': 'Strateji 2 — MA Destek DCA',
    's05.h3': 'Strateji 3 — S/R Sekme (Varsayılan)',
    's05.callout1': '<div class="callout-label">Giriş Koşulları — 3\'ü de Gerekli</div><strong>①</strong> Fiyat bir S/R seviyesinin ±%0.4 içinde &nbsp;|&nbsp; <strong>②</strong> Momentum yönü onaylar (long için sekme, short için reddetme) &nbsp;|&nbsp; <strong>③</strong> SL mesafesi girişten %1–7 (gürültü ve aşırı geniş durakları filtreler)',
    's05.h4': 'Strateji 4 — MA Kesişimi + RSI Onayı',
    's05.h5': 'Strateji 5 — Bollinger Bandı Ortalamaya Dönüş',
    's05.h6': 'Strateji 6 — Kırılım + Hacim Onayı',
    's05.h7': 'Strateji 7 — MA Şerit Long',
    's05.h8': 'Strateji 8 — MACD Uyumsuzluğu',
    's05.callout2': '<div class="callout-label">Yüksek Risk</div>Uyumsuzluk, çözülmeden önce birçok mum boyunca devam edebilir. Bu stratejiyle muhafazakâr DCA sayısı (2–3 giriş) ve daha küçük pozisyon boyutları kullanın.',
    's05.h9': 'Strateji 9 — Fonlama Oranı Zıt Yönlü',
    's05.callout3': '<div class="callout-label">Yüksek Risk</div>Fonlama oranları tek başına yönü belirleyemez. Trend piyasalarında aşırı fonlama günlerce devam edebilir. Trend filtresiyle birlikte kullanın veya küçük pozisyon boyutları tercih edin.',
    's05.h10': 'Strateji 10 — ATR Trend Takip',
},
'es': {
    's05.p1': 'AYILON soporta 10 estrategias de trading. Su plan de suscripción determina cuáles están disponibles. Todas las estrategias comparten la misma lógica de entrada DCA, dimensionamiento de posición y marco de gestión de riesgo descrito en las secciones 06–13.',
    's05.h1': 'Estrategia 1 — RSI Sobrevendido DCA Long',
    's05.h2': 'Estrategia 2 — MA Soporte DCA',
    's05.h3': 'Estrategia 3 — Rebote S/R (Por Defecto)',
    's05.callout1': '<div class="callout-label">Condiciones de Entrada — Las 3 son Necesarias</div><strong>①</strong> Precio dentro del ±0.4% de un nivel S/R &nbsp;|&nbsp; <strong>②</strong> El momentum confirma la dirección (rebote para long, rechazo para short) &nbsp;|&nbsp; <strong>③</strong> Distancia SL 1–7% desde la entrada (filtra ruido y stops demasiado amplios)',
    's05.h4': 'Estrategia 4 — Cruce MA + Confirmación RSI',
    's05.h5': 'Estrategia 5 — Reversión a la Media Bollinger Band',
    's05.h6': 'Estrategia 6 — Ruptura + Confirmación de Volumen',
    's05.h7': 'Estrategia 7 — MA Ribbon Long',
    's05.h8': 'Estrategia 8 — Divergencia MACD',
    's05.callout2': '<div class="callout-label">Alto Riesgo</div>La divergencia puede persistir durante muchas velas antes de resolverse. Use conteos DCA conservadores (2–3 entradas) y tamaños de posición más pequeños con esta estrategia.',
    's05.h9': 'Estrategia 9 — Contrarian de Tasa de Financiamiento',
    's05.callout3': '<div class="callout-label">Alto Riesgo</div>Las tasas de financiamiento por sí solas no determinan la dirección. El financiamiento extremo puede continuar por días en mercados de tendencia. Combine con un filtro de tendencia o use tamaños de posición pequeños.',
    's05.h10': 'Estrategia 10 — Seguimiento de Tendencia ATR',
},
'pt': {
    's05.p1': 'AYILON suporta 10 estratégias de trading. Seu plano de assinatura determina quais estão disponíveis. Todas as estratégias compartilham a mesma lógica de entrada DCA, dimensionamento de posição e framework de gestão de risco descrito nas seções 06–13.',
    's05.h1': 'Estratégia 1 — RSI Sobrevendido DCA Long',
    's05.h2': 'Estratégia 2 — MA Suporte DCA',
    's05.h3': 'Estratégia 3 — Ricochete S/R (Padrão)',
    's05.callout1': '<div class="callout-label">Condições de Entrada — As 3 São Necessárias</div><strong>①</strong> Preço dentro de ±0.4% de um nível S/R &nbsp;|&nbsp; <strong>②</strong> O momentum confirma a direção (ricochete para long, rejeição para short) &nbsp;|&nbsp; <strong>③</strong> Distância SL 1–7% da entrada (filtra ruído e stops muito amplos)',
    's05.h4': 'Estratégia 4 — Cruzamento MA + Confirmação RSI',
    's05.h5': 'Estratégia 5 — Reversão à Média Bollinger Band',
    's05.h6': 'Estratégia 6 — Ruptura + Confirmação de Volume',
    's05.h7': 'Estratégia 7 — MA Ribbon Long',
    's05.h8': 'Estratégia 8 — Divergência MACD',
    's05.callout2': '<div class="callout-label">Alto Risco</div>A divergência pode persistir por muitas velas antes de se resolver. Use contagens DCA conservadoras (2–3 entradas) e tamanhos de posição menores com esta estratégia.',
    's05.h9': 'Estratégia 9 — Contrarian de Taxa de Financiamento',
    's05.callout3': '<div class="callout-label">Alto Risco</div>As taxas de financiamento por si só não determinam a direção. O financiamento extremo pode continuar por dias em mercados de tendência. Combine com um filtro de tendência ou use posições pequenas.',
    's05.h10': 'Estratégia 10 — Seguimento de Tendência ATR',
},
'id': {
    's05.p1': 'AYILON mendukung 10 strategi trading. Paket langganan Anda menentukan mana yang tersedia. Semua strategi berbagi logika entri DCA, ukuran posisi, dan kerangka manajemen risiko yang sama yang dijelaskan di bagian 06–13.',
    's05.h1': 'Strategi 1 — RSI Oversold DCA Long',
    's05.h2': 'Strategi 2 — MA Support DCA',
    's05.h3': 'Strategi 3 — S/R Bounce (Default)',
    's05.callout1': '<div class="callout-label">Kondisi Entri — Ketiganya Diperlukan</div><strong>①</strong> Harga dalam ±0.4% dari level S/R &nbsp;|&nbsp; <strong>②</strong> Momentum mengonfirmasi arah (bounce untuk long, penolakan untuk short) &nbsp;|&nbsp; <strong>③</strong> Jarak SL 1–7% dari entri (menyaring noise dan stop yang terlalu lebar)',
    's05.h4': 'Strategi 4 — MA Crossover + Konfirmasi RSI',
    's05.h5': 'Strategi 5 — Bollinger Band Mean Reversion',
    's05.h6': 'Strategi 6 — Breakout + Konfirmasi Volume',
    's05.h7': 'Strategi 7 — MA Ribbon Long',
    's05.h8': 'Strategi 8 — MACD Divergence',
    's05.callout2': '<div class="callout-label">Risiko Tinggi</div>Divergence dapat bertahan selama banyak lilin sebelum terselesaikan. Gunakan jumlah DCA yang konservatif (2–3 entri) dan ukuran posisi yang lebih kecil dengan strategi ini.',
    's05.h9': 'Strategi 9 — Funding Rate Contrarian',
    's05.callout3': '<div class="callout-label">Risiko Tinggi</div>Funding rate saja tidak menentukan arah. Funding ekstrem dapat berlanjut selama berhari-hari di pasar yang sedang tren. Kombinasikan dengan filter tren atau gunakan ukuran posisi kecil.',
    's05.h10': 'Strategi 10 — ATR Trend Following',
},
})

# S06 translations
add({
'ko': {
    's06.p1': 'AYILON은 <strong>고정 비율</strong> 포지션 크기 모델을 사용합니다. 거래당 리스크로 감당할 자본의 비율을 설정하면 봇이 이에 따라 계약 크기를 계산합니다. 이를 통해 계좌 잔고 변화에 관계없이 일관된 리스크가 유지됩니다.',
    's06.card1': '기본값. SL이 진입 #1에서 발생할 경우 손실을 감수할 자본의 금액입니다.',
    's06.card2': '오늘의 누적 실현 손실 + 평가 손실이 이 수준에 도달하면 봇이 당일 거래를 중단합니다.',
    's06.card3': '사용자 설정값. 각 진입은 첫 진입가와 SL 사이에 동일한 간격으로 배치됩니다.',
    's06.h1': 'DCA 진입 간격 — N등분 방식',
    's06.p2': 'DCA 진입 간에 고정된 가격 간격 대신, AYILON은 첫 진입가와 손절 사이의 구간을 N등분합니다. 이는 SL이 멀거나 가깝더라도 모든 진입이 유효한 거래 구간 내에 있도록 보장합니다.',
    's06.p3': '<strong>예시 (롱, 3번 진입):</strong> 첫 진입가 100,000, SL(스윙 저점) 97,000. 간격 = 1,000. 진입: 100,000 → 99,000 → 98,000. SL: 97,000.',
    's06.h2': '진입 크기 모드',
    's06.callout1': '<div class="callout-label">마틴게일 경고</div>2× 배수와 3번 진입 시 총 자본 사용량은 <strong>첫 진입 크기의 7배</strong>입니다. 4번 진입 시는 15배입니다. 계좌에 모든 계획된 진입을 커버할 충분한 잔고가 있는지 확인하세요, 그렇지 않으면 마지막 DCA 주문이 체결되지 않을 수 있습니다.',
    's06.callout2': '<div class="callout-label">리스크 상한</div>설정과 관계없이 단일 진입이 <strong>자본의 40%</strong>를 초과하지 않습니다. 계산된 크기가 이 상한을 초과하면 봇이 이를 줄이고 경고를 기록합니다.',
},
'ja': {
    's06.p1': 'AYILONは<strong>固定比率</strong>ポジションサイジングモデルを使用します。取引ごとにリスクにさらす資産のパーセンテージを定義すると、ボットがそれに応じてコントラクトサイズを計算します。これにより口座残高の変化に関わらずリスクが一定に保たれます。',
    's06.card1': 'デフォルト。エントリー#1でSLが発動した場合に損失を許容する資産の金額です。',
    's06.card2': '当日の累積実現損失＋評価損失がこのレベルに達した時点でボットは当日の取引を停止します。',
    's06.card3': 'ユーザー設定。各エントリーは最初のエントリー価格とSLの間に等間隔で配置されます。',
    's06.h1': 'DCAエントリー間隔 — N等分方式',
    's06.p2': 'DCAエントリー間の固定価格間隔の代わりに、AYILONは最初のエントリー価格と損切りの間のゾーンをN等分します。これにより、SLが遠くても近くても、すべてのエントリーが有効な取引ゾーン内に収まることが保証されます。',
    's06.p3': '<strong>例（ロング、3エントリー）：</strong>最初のエントリーが100,000、SL（スイングロー）が97,000。ギャップ = 1,000。エントリー：100,000 → 99,000 → 98,000。SL：97,000。',
    's06.h2': 'エントリーサイジングモード',
    's06.callout1': '<div class="callout-label">マーチンゲール警告</div>2×乗数と3エントリーの場合、総使用資本は<strong>最初のエントリーサイズの7倍</strong>です。4エントリーでは15倍になります。すべての計画エントリーをカバーする十分な残高があることを確認してください。',
    's06.callout2': '<div class="callout-label">リスク上限</div>設定に関わらず、単一のエントリーは<strong>資産の40%</strong>を超えません。計算されたサイズがこの上限を超える場合、ボットはそれを削減して警告を記録します。',
},
'zh': {
    's06.p1': 'AYILON采用<strong>固定比例</strong>仓位管理模型。您设定每笔交易愿意承担的资金百分比，机器人据此计算合约大小。无论账户余额如何变化，这都能保持风险的一致性。',
    's06.card1': '默认值。止损在第1次入场触发时愿意承受的资金亏损额。',
    's06.card2': '当今日累计已实现亏损+浮亏达到此水平时，机器人暂停当日交易。',
    's06.card3': '用户配置。每次入场均匀分布在第一次入场价格和止损之间。',
    's06.h1': 'DCA入场间距 — N等分方式',
    's06.p2': '不是在DCA入场之间设置固定价格间隔，而是AYILON将第一次入场价格到止损之间的区间划分为N等份。无论止损距离远近，这都能保证所有入场点始终在有效交易区间内。',
    's06.p3': '<strong>示例（做多，3次入场）：</strong>第一次入场价100,000，SL（波段低点）97,000。间距=1,000。入场点：100,000→99,000→98,000。止损：97,000。',
    's06.h2': '入场仓位模式',
    's06.callout1': '<div class="callout-label">马丁格尔警告</div>2倍乘数、3次入场时，总使用资金为<strong>第一次入场资金的7倍</strong>。4次入场则为15倍。确保账户有足够余额覆盖所有计划入场，否则最后一次DCA可能无法成交。',
    's06.callout2': '<div class="callout-label">风险上限</div>无论设置如何，单次入场不会超过<strong>资金的40%</strong>。若计算出的大小超过此上限，机器人会自动缩减并记录警告。',
},
'vi': {
    's06.p1': 'AYILON sử dụng mô hình quản lý kích cỡ vị thế <strong>Tỷ lệ Cố định</strong>. Bạn xác định tỷ lệ vốn muốn rủi ro mỗi giao dịch, bot tính toán kích cỡ hợp đồng tương ứng. Điều này giữ rủi ro nhất quán bất kể số dư tài khoản thay đổi.',
    's06.card1': 'Mặc định. Số vốn bạn sẵn sàng thua lỗ nếu SL kích hoạt ở lần vào lệnh #1.',
    's06.card2': 'Bot tạm dừng ngày khi lỗ đã thực hiện tích lũy + lỗ nổi đạt mức này.',
    's06.card3': 'Do người dùng cấu hình. Mỗi lần vào lệnh cách đều nhau giữa giá vào lệnh đầu tiên và SL.',
    's06.h1': 'Khoảng cách vào lệnh DCA — Chia N phần bằng nhau',
    's06.p2': 'Thay vì khoảng cách giá cố định giữa các lần vào DCA, AYILON chia vùng giữa giá vào lệnh đầu tiên và điểm dừng lỗ thành N phần bằng nhau. Điều này đảm bảo tất cả các lần vào đều nằm trong vùng giao dịch hợp lệ bất kể SL gần hay xa.',
    's06.p3': '<strong>Ví dụ (Long, 3 lần vào):</strong> Lần vào đầu tiên 100,000, SL (đáy swing) 97,000. Khoảng cách = 1,000. Các lần vào: 100,000 → 99,000 → 98,000. SL: 97,000.',
    's06.h2': 'Chế độ kích cỡ vào lệnh',
    's06.callout1': '<div class="callout-label">Cảnh báo Martingale</div>Với hệ số 2× và 3 lần vào, tổng vốn sử dụng là <strong>7× kích cỡ lần vào đầu tiên</strong>. Với 4 lần vào là 15×. Đảm bảo tài khoản có đủ số dư để đáp ứng tất cả các lần vào đã lên kế hoạch.',
    's06.callout2': '<div class="callout-label">Giới hạn rủi ro</div>Bất kể cài đặt, không có lần vào lệnh đơn nào vượt quá <strong>40% vốn</strong>. Nếu kích cỡ tính toán vượt giới hạn này, bot sẽ giảm xuống và ghi cảnh báo.',
},
'ru': {
    's06.p1': 'AYILON использует модель управления размером позиции <strong>Фиксированная доля</strong>. Вы задаёте процент капитала, которым готовы рисковать в сделке, а бот рассчитывает размер контракта. Это обеспечивает постоянный риск вне зависимости от изменений баланса.',
    's06.card1': 'По умолчанию. Сумма капитала, которую вы готовы потерять при срабатывании SL на входе #1.',
    's06.card2': 'Бот останавливает торговлю на день, когда совокупные реализованные убытки + текущие убытки достигают этого уровня.',
    's06.card3': 'Настраивается пользователем. Каждый вход равномерно распределяется между первой ценой входа и SL.',
    's06.h1': 'Расстояние между входами DCA — метод N равных частей',
    's06.p2': 'Вместо фиксированного ценового интервала между входами DCA, AYILON делит зону между первой ценой входа и уровнем стопа на N равных частей. Это гарантирует, что все входы останутся в пределах зоны торговой идеи независимо от расстояния до SL.',
    's06.p3': '<strong>Пример (лонг, 3 входа):</strong> Первый вход по 100,000, SL (минимум свечи) по 97,000. Шаг = 1,000. Входы: 100,000 → 99,000 → 98,000. SL: 97,000.',
    's06.h2': 'Режимы размера входов',
    's06.callout1': '<div class="callout-label">Предупреждение о мартингейле</div>При множителе 2× и 3 входах общий используемый капитал составляет <strong>7× размер первого входа</strong>. При 4 входах — 15×. Убедитесь, что на счёте достаточно средств для всех запланированных входов.',
    's06.callout2': '<div class="callout-label">Ограничение риска</div>Вне зависимости от настроек ни один вход не превысит <strong>40% капитала</strong>. Если рассчитанный размер превышает этот лимит, бот уменьшает его и записывает предупреждение.',
},
'tr': {
    's06.p1': 'AYILON <strong>Sabit Oransal</strong> pozisyon büyüklüğü modeli kullanır. Her işlem için riske atmak istediğiniz sermayenin yüzdesini belirlersiniz ve bot buna göre kontrat büyüklüğünü hesaplar. Bu, hesap bakiyesindeki değişikliklerden bağımsız olarak riski tutarlı tutar.',
    's06.card1': 'Varsayılan. SL giriş #1\'de tetiklenirse kaybetmeye razı olduğunuz sermaye miktarı.',
    's06.card2': 'Bugünkü birikimli gerçekleşen zarar + değerleme kaybı bu seviyeye ulaştığında bot o günlük işlemleri durdurur.',
    's06.card3': 'Kullanıcı tarafından ayarlanır. Her giriş, ilk giriş fiyatı ile SL arasına eşit aralıklarla yerleştirilir.',
    's06.h1': 'DCA Giriş Aralığı — N Eşit Parça Yöntemi',
    's06.p2': 'DCA girişleri arasında sabit bir fiyat aralığı yerine AYILON, ilk giriş fiyatı ile zararı durdur arasındaki bölgeyi N eşit parçaya böler. Bu, SL ne kadar uzak ya da yakın olursa olsun tüm girişlerin geçerli işlem bölgesi içinde kalmasını garanti eder.',
    's06.p3': '<strong>Örnek (Long, 3 giriş):</strong> İlk giriş 100.000\'de, SL (swing dip) 97.000\'de. Aralık = 1.000. Girişler: 100.000 → 99.000 → 98.000. SL: 97.000.',
    's06.h2': 'Giriş Boyutlandırma Modları',
    's06.callout1': '<div class="callout-label">Martingale Uyarısı</div>2× çarpan ve 3 girişte toplam kullanılan sermaye <strong>ilk giriş boyutunun 7 katıdır</strong>. 4 girişte 15 kattır. Tüm planlı girişleri karşılayacak yeterli bakiye olduğundan emin olun.',
    's06.callout2': '<div class="callout-label">Risk Sınırı</div>Ayarlardan bağımsız olarak hiçbir tek giriş <strong>sermayenin %40\'ını</strong> aşmaz. Hesaplanan boyut bu sınırı aşarsa bot onu azaltır ve uyarı kaydeder.',
},
'es': {
    's06.p1': 'AYILON usa un modelo de dimensionamiento de posición de <strong>Fracción Fija</strong>. Define qué porcentaje de su capital arriesgar por operación y el bot calcula el tamaño del contrato en consecuencia. Esto mantiene el riesgo consistente independientemente de los cambios en el saldo de la cuenta.',
    's06.card1': 'Por defecto. Cantidad de capital que está dispuesto a perder si el SL se activa en la entrada #1.',
    's06.card2': 'El bot pausa el día cuando las pérdidas realizadas acumuladas + pérdidas flotantes alcanzan este nivel.',
    's06.card3': 'Configurado por el usuario. Cada entrada está igualmente espaciada entre el precio de la primera entrada y el SL.',
    's06.h1': 'Espaciado de Entradas DCA — N Partes Iguales',
    's06.p2': 'En lugar de un intervalo de precio fijo entre entradas DCA, AYILON divide la zona entre el precio de la primera entrada y el stop loss en N partes iguales. Esto garantiza que todas las entradas permanezcan dentro de la zona de trade válida, independientemente de qué tan lejos o cerca esté el SL.',
    's06.p3': '<strong>Ejemplo (Long, 3 entradas):</strong> Primera entrada en 100,000, SL (mínimo swing) en 97,000. Brecha = 1,000. Entradas: 100,000 → 99,000 → 98,000. SL: 97,000.',
    's06.h2': 'Modos de Tamaño de Entrada',
    's06.callout1': '<div class="callout-label">Advertencia Martingala</div>Con multiplicador 2× y 3 entradas, el capital total usado es <strong>7× el tamaño de la primera entrada</strong>. Con 4 entradas es 15×. Asegúrese de que su cuenta tenga saldo suficiente para cubrir todas las entradas planeadas.',
    's06.callout2': '<div class="callout-label">Límite de Riesgo</div>Sin importar la configuración, ninguna entrada única superará el <strong>40% del capital</strong>. Si el tamaño calculado excede este límite, el bot lo reduce y registra una advertencia.',
},
'pt': {
    's06.p1': 'AYILON usa um modelo de dimensionamento de posição de <strong>Fração Fixa</strong>. Você define qual porcentagem do seu capital arriscar por operação e o bot calcula o tamanho do contrato de acordo. Isso mantém o risco consistente independentemente das mudanças no saldo da conta.',
    's06.card1': 'Padrão. Quantidade de capital que está disposto a perder se o SL for ativado na entrada #1.',
    's06.card2': 'Bot pausa o dia quando as perdas realizadas acumuladas + perdas flutuantes atingem este nível.',
    's06.card3': 'Configurado pelo usuário. Cada entrada é igualmente espaçada entre o preço da primeira entrada e o SL.',
    's06.h1': 'Espaçamento de Entradas DCA — N Partes Iguais',
    's06.p2': 'Em vez de um intervalo de preço fixo entre entradas DCA, AYILON divide a zona entre o preço da primeira entrada e o stop loss em N partes iguais. Isso garante que todas as entradas permaneçam dentro da zona de trade válida, independentemente de quão longe ou perto o SL estiver.',
    's06.p3': '<strong>Exemplo (Long, 3 entradas):</strong> Primeira entrada em 100,000, SL (mínimo swing) em 97,000. Lacuna = 1,000. Entradas: 100,000 → 99,000 → 98,000. SL: 97,000.',
    's06.h2': 'Modos de Tamanho de Entrada',
    's06.callout1': '<div class="callout-label">Aviso de Martingale</div>Com multiplicador 2× e 3 entradas, o capital total usado é <strong>7× o tamanho da primeira entrada</strong>. Com 4 entradas é 15×. Certifique-se de que sua conta tenha saldo suficiente para cobrir todas as entradas planejadas.',
    's06.callout2': '<div class="callout-label">Limite de Risco</div>Independentemente das configurações, nenhuma entrada única excederá <strong>40% do capital</strong>. Se o tamanho calculado exceder este limite, o bot o reduz e registra um aviso.',
},
'id': {
    's06.p1': 'AYILON menggunakan model ukuran posisi <strong>Fraksi Tetap</strong>. Anda menentukan persentase ekuitas yang ingin Anda risiko per perdagangan, dan bot menghitung ukuran kontrak sesuai. Ini menjaga risiko tetap konsisten terlepas dari perubahan saldo akun.',
    's06.card1': 'Default. Jumlah ekuitas yang bersedia Anda rugikan jika SL terkena pada entri #1.',
    's06.card2': 'Bot berhenti untuk hari itu ketika kerugian terealisasi kumulatif + kerugian mengambang mencapai level ini.',
    's06.card3': 'Dikonfigurasi pengguna. Setiap entri berjarak sama antara harga entri pertama dan SL.',
    's06.h1': 'Spasi Entri DCA — Metode N Bagian Sama',
    's06.p2': 'Alih-alih interval harga tetap antara entri DCA, AYILON membagi zona antara harga entri pertama dan stop loss menjadi N bagian yang sama. Ini menjamin semua entri tetap dalam zona trade yang valid terlepas dari seberapa jauh atau dekat SL.',
    's06.p3': '<strong>Contoh (Long, 3 entri):</strong> Entri pertama di 100.000, SL (swing low) di 97.000. Celah = 1.000. Entri: 100.000 → 99.000 → 98.000. SL: 97.000.',
    's06.h2': 'Mode Ukuran Entri',
    's06.callout1': '<div class="callout-label">Peringatan Martingale</div>Dengan pengali 2× dan 3 entri, total modal yang digunakan adalah <strong>7× ukuran entri pertama</strong>. Dengan 4 entri adalah 15×. Pastikan akun Anda memiliki saldo yang cukup untuk menutup semua entri yang direncanakan.',
    's06.callout2': '<div class="callout-label">Batas Risiko</div>Terlepas dari pengaturan, tidak ada entri tunggal yang melebihi <strong>40% ekuitas</strong>. Jika ukuran yang dihitung melebihi batas ini, bot menguranginya dan mencatat peringatan.',
},
})

# S07 translations
add({
'ko': {
    's07.h1': '규칙 1 — 방향 전환 금지',
    's07.p1': '봇이 이미 한 방향으로 오픈 포지션을 보유하고 있는 경우(예: 롱), 해당 포지션이 완전히 종료될 때까지 <strong>절대 숏을 열지 않습니다</strong>. 이는 동시에 시장의 양쪽에 걸리는 것을 방지합니다.',
    's07.h2': '규칙 2 — 최대 진입 수',
    's07.p2': '봇은 현재 셋업에서 몇 번 진입했는지 추적합니다. 사용자 설정 <code>numEntries</code> 한도(기본값: 3)에 도달하면 해당 셋업에 더 이상 진입하지 않습니다.',
    's07.h3': '규칙 3 — DCA 구간 제한',
    's07.p3': '모든 DCA 진입은 신호 발생 시 미리 계산되며 <strong>첫 진입가와 손절 레벨 사이</strong>에 있어야 합니다. 봇은 SL 가격 또는 그 이하에서는 진입하지 않습니다. 해당 cron 틱이 실행될 때 현재 시장가가 이미 예정된 진입 레벨 아래에 있으면 해당 진입은 건너뜁니다.',
    's07.callout1': '<div class="callout-label">왜 중요한가</div>첫 진입과 SL 사이의 구간에 진입을 분산시키면 모든 DCA 매수가 구조적 거래 아이디어 내에 있게 됩니다. SL이 트리거되면 몇 번 진입이 체결되었든 최대 손실이 제한됩니다. 진입은 무효화 레벨 아래의 가격을 추격하지 않습니다.',
},
'ja': {
    's07.h1': 'ルール1 — 方向転換禁止',
    's07.p1': 'ボットがすでに一方向でオープンポジションを持っている場合（例：ロング）、そのポジションが完全にクローズするまで<strong>ショートは絶対に開きません</strong>。これにより同時に市場の両サイドに掛かることを防ぎます。',
    's07.h2': 'ルール2 — 最大エントリー数',
    's07.p2': 'ボットは現在のセットアップで何回エントリーしたかを追跡します。ユーザー設定の<code>numEntries</code>上限（デフォルト：3）に達すると、このセットアップではそれ以上エントリーしません。',
    's07.h3': 'ルール3 — DCAゾーン制限',
    's07.p3': 'すべてのDCAエントリーはシグナル時に事前計算され、<strong>最初のエントリー価格とSLレベルの間</strong>に収まる必要があります。ボットはSL価格以下ではエントリーしません。',
    's07.callout1': '<div class="callout-label">なぜ重要か</div>最初のエントリーとSLの間のゾーンにエントリーを分散させることで、すべてのDCA購入が構造的な取引アイデア内に収まります。SLが発動した場合、何回エントリーが成立したかに関わらず最大損失は限定されます。</div>',
},
'zh': {
    's07.h1': '规则1 — 禁止方向切换',
    's07.p1': '如果机器人已持有某方向的持仓（如多头），在该仓位完全平仓之前，<strong>绝对不会开空</strong>。这防止了同时被市场双向套住的情况。',
    's07.h2': '规则2 — 最大入场次数',
    's07.p2': '机器人追踪当前交易中已入场几次。一旦达到用户设置的<code>numEntries</code>上限（默认：3次），该次交易不再允许进一步入场。',
    's07.h3': '规则3 — DCA区间约束',
    's07.p3': '所有DCA入场在信号触发时预先计算完毕，且必须位于<strong>第一次入场价格与止损位之间</strong>。机器人不会在止损价格处或以下入场。',
    's07.callout1': '<div class="callout-label">为何重要</div>将入场点分散在第一次入场与止损之间的区间内，使所有DCA加仓都处于结构化交易逻辑范围内。如果止损触发，无论有多少次入场被成交，最大亏损都是有限的。</div>',
},
'vi': {
    's07.h1': 'Quy tắc 1 — Không đổi chiều',
    's07.p1': 'Nếu bot đang giữ vị thế mở theo một hướng (ví dụ: Long), nó sẽ <strong>không bao giờ mở Short</strong> cho đến khi vị thế đó đóng hoàn toàn. Điều này ngăn việc cùng lúc mắc kẹt ở cả hai phía thị trường.',
    's07.h2': 'Quy tắc 2 — Số lần vào lệnh tối đa',
    's07.p2': 'Bot theo dõi số lần đã vào lệnh trong thiết lập hiện tại. Khi đạt giới hạn <code>numEntries</code> do người dùng cấu hình (mặc định: 3), không cho phép thêm lần vào lệnh nào cho thiết lập này.',
    's07.h3': 'Quy tắc 3 — Giới hạn vùng DCA',
    's07.p3': 'Tất cả các lần vào DCA được tính trước tại thời điểm có tín hiệu và phải nằm <strong>giữa giá vào lệnh đầu tiên và mức stop loss</strong>. Bot không đặt lệnh ở hoặc dưới giá SL.',
    's07.callout1': '<div class="callout-label">Tại sao quan trọng</div>Phân bổ các lần vào trong vùng giữa lần vào đầu tiên và SL giữ cho tất cả giao dịch DCA nằm trong ý tưởng giao dịch có cấu trúc. Nếu SL kích hoạt, tổn thất tối đa bị giới hạn bất kể bao nhiêu lần vào đã được khớp.</div>',
},
'ru': {
    's07.h1': 'Правило 1 — Запрет смены направления',
    's07.p1': 'Если бот уже держит открытую позицию в одном направлении (например, лонг), он <strong>никогда не откроет шорт</strong>, пока эта позиция не будет полностью закрыта. Это предотвращает одновременное удержание позиций в обоих направлениях.',
    's07.h2': 'Правило 2 — Максимальное количество входов',
    's07.p2': 'Бот отслеживает, сколько входов было сделано в текущем сетапе. Когда достигается настроенный пользователем лимит <code>numEntries</code> (по умолчанию: 3), новые входы для этого сетапа не разрешаются.',
    's07.h3': 'Правило 3 — Зона DCA',
    's07.p3': 'Все входы DCA заранее рассчитываются в момент сигнала и должны находиться <strong>между первой ценой входа и уровнем стопа</strong>. Бот не размещает вход по цене стопа или ниже.',
    's07.callout1': '<div class="callout-label">Почему это важно</div>Распределение входов в зоне между первым входом и SL удерживает все покупки DCA в рамках структурированной торговой идеи. При срабатывании SL максимальный убыток ограничен вне зависимости от числа заполненных входов.</div>',
},
'tr': {
    's07.h1': 'Kural 1 — Yön Değişikliği Yok',
    's07.p1': 'Bot zaten bir yönde açık pozisyon tutuyorsa (örn. Long), o pozisyon tamamen kapanana kadar <strong>asla Short açmaz</strong>. Bu, aynı anda piyasanın iki tarafında kalmayı önler.',
    's07.h2': 'Kural 2 — Maksimum Giriş Sayısı',
    's07.p2': 'Bot, mevcut kurulumda kaç giriş yapıldığını takip eder. Kullanıcı tarafından ayarlanan <code>numEntries</code> limiti (varsayılan: 3) ulaşıldığında, bu kurulum için başka girişe izin verilmez.',
    's07.h3': 'Kural 3 — DCA Bölge Sınırlaması',
    's07.p3': 'Tüm DCA girişleri sinyal zamanında önceden hesaplanır ve <strong>ilk giriş fiyatı ile zararı durdur seviyesi arasında</strong> olmalıdır. Bot, SL fiyatında veya altında giriş yapmaz.',
    's07.callout1': '<div class="callout-label">Neden Önemli</div>Girişleri ilk giriş ile SL arasındaki bölgeye yaymak, tüm DCA alımlarının yapılandırılmış işlem fikri içinde kalmasını sağlar. SL tetiklenirse, kaç giriş dolmuş olursa olsun maksimum kayıp sınırlı kalır.</div>',
},
'es': {
    's07.h1': 'Regla 1 — Sin Cambio de Dirección',
    's07.p1': 'Si el bot ya mantiene una posición abierta en una dirección (p. ej., LONG), <strong>nunca abrirá un SHORT</strong> hasta que esa posición esté completamente cerrada. Esto evita quedar atrapado en ambos lados del mercado simultáneamente.',
    's07.h2': 'Regla 2 — Número Máximo de Entradas',
    's07.p2': 'El bot rastrea cuántas entradas se han colocado en el setup actual. Una vez que se alcanza el límite <code>numEntries</code> configurado por el usuario (por defecto: 3), no se permiten más entradas para este setup.',
    's07.h3': 'Regla 3 — Contención de Zona DCA',
    's07.p3': 'Todas las entradas DCA se pre-calculan en el momento de la señal y deben caer <strong>entre el precio de la primera entrada y el nivel de stop loss</strong>. El bot no colocará una entrada en o más allá del precio SL.',
    's07.callout1': '<div class="callout-label">Por Qué Es Importante</div>Espaciar las entradas en la zona entre la primera entrada y el SL mantiene todas las compras DCA dentro de la idea de trade estructurada. Si el SL se activa, la pérdida máxima está acotada independientemente de cuántas entradas se hayan completado.</div>',
},
'pt': {
    's07.h1': 'Regra 1 — Sem Mudança de Direção',
    's07.p1': 'Se o bot já mantém uma posição aberta em uma direção (ex: LONG), ele <strong>nunca abrirá um SHORT</strong> até que essa posição seja totalmente fechada. Isso evita ficar preso em ambos os lados do mercado simultaneamente.',
    's07.h2': 'Regra 2 — Contagem Máxima de Entradas',
    's07.p2': 'O bot rastreia quantas entradas foram colocadas no setup atual. Uma vez atingido o limite <code>numEntries</code> configurado pelo usuário (padrão: 3), não são permitidas mais entradas para este setup.',
    's07.h3': 'Regra 3 — Contenção de Zona DCA',
    's07.p3': 'Todas as entradas DCA são pré-calculadas no momento do sinal e devem cair <strong>entre o preço da primeira entrada e o nível de stop loss</strong>. O bot não colocará uma entrada no ou além do preço SL.',
    's07.callout1': '<div class="callout-label">Por Que Isso Importa</div>Espaçar as entradas na zona entre a primeira entrada e o SL mantém todas as compras DCA dentro da ideia de trade estruturada. Se o SL for ativado, a perda máxima é limitada independentemente de quantas entradas foram preenchidas.</div>',
},
'id': {
    's07.h1': 'Aturan 1 — Tidak Ada Pembalikan Arah',
    's07.p1': 'Jika bot sudah memegang posisi terbuka di satu arah (mis. LONG), bot <strong>tidak akan pernah membuka SHORT</strong> sampai posisi tersebut ditutup sepenuhnya. Ini mencegah tertangkap di kedua sisi pasar secara bersamaan.',
    's07.h2': 'Aturan 2 — Jumlah Entri Maksimum',
    's07.p2': 'Bot melacak berapa banyak entri yang telah ditempatkan dalam setup saat ini. Setelah batas <code>numEntries</code> yang dikonfigurasi pengguna (default: 3) tercapai, tidak ada entri lebih lanjut yang diizinkan untuk setup ini.',
    's07.h3': 'Aturan 3 — Pembatasan Zona DCA',
    's07.p3': 'Semua entri DCA dihitung terlebih dahulu pada waktu sinyal dan harus berada <strong>antara harga entri pertama dan level stop loss</strong>. Bot tidak akan menempatkan entri pada atau di luar harga SL.',
    's07.callout1': '<div class="callout-label">Mengapa Ini Penting</div>Menyebarkan entri di zona antara entri pertama dan SL menjaga semua pembelian DCA dalam ide trade yang terstruktur. Jika SL terpicu, kerugian maksimum dibatasi terlepas dari berapa banyak entri yang terisi.</div>',
},
})

# S08 remaining translations
add({
'ko': {
    's08.h1': 'TP 레벨 선택',
    's08.h2': 'TP 도달 시 처리 과정',
    's08.f1.name': '포지션 절반 청산 (반 익절)',
    's08.f1.desc': '봇이 <strong>보유한 총 수량의 정확히 절반</strong>을 청산하는 시장가 주문을 실행합니다. 예: 0.01 BTC → TP 레벨에서 0.005 BTC 매도. 이 절반에 대한 수익이 확정됩니다.',
    's08.f2.name': 'SL을 평균 진입가로 이동 (본절)',
    's08.f2.desc': '손절이 모든 진입의 가중 평균 진입가로 이동합니다. 가격이 이 레벨로 되돌아오면 나머지 절반이 본절에 청산됩니다 — 손실 없음.',
    's08.f3.name': '나머지 절반 무료 보유',
    's08.f3.desc': '두 번째 절반에 대한 고정 TP가 없습니다. 본절 SL이 닿거나 다음 레벨이 도달할 때까지 오픈 상태로 유지되어 첫 번째 레벨 이후의 추가 움직임을 포착합니다.',
    's08.callout2': '<div class="callout-label">로직</div>지지선에서 빡빡한 SL(3–6%)로 진입합니다. 가격이 다음 저항선으로 반등하면 → 절반 청산, 수익 확정. 평균 진입가로 되돌아오면 → 나머지를 본절에 청산(손실 없음). 계속 오르면 → 두 번째 절반을 무료로 보유. 최악의 경우: 첫 번째 절반에서 소정의 수익, 두 번째에서 0.',
},
'ja': {
    's08.h1': 'TPレベル選択',
    's08.h2': 'TP到達時の処理',
    's08.f1.name': 'ポジションの半分を決済（半分利確）',
    's08.f1.desc': 'ボットが<strong>保有総量の正確に半分</strong>を決済する成行注文を発注します。例：0.01 BTC → TPレベルで0.005 BTCを売却。この半分の利益が確定します。',
    's08.f2.name': 'SLを平均エントリー価格へ移動（ブレークイーブン）',
    's08.f2.desc': 'ストップロスがすべてのエントリーの加重平均エントリー価格に移動します。価格がこのレベルに戻った場合、残りの半分がブレークイーブンで決済されます（損失なし）。',
    's08.f3.name': '残り半分は利益確定せず保有',
    's08.f3.desc': '第2の半分に固定TPはありません。ブレークイーブンSLが触れるか次のレベルに達するまでオープンのまま保持され、最初のレベルを超えた追加の動きを取り込みます。',
    's08.callout2': '<div class="callout-label">ロジック</div>タイトなSL（3〜6%）でサポートにエントリー。次のレジスタンスへバウンス→半分決済、利益確定。平均エントリーへ戻る→残りをブレークイーブンで決済（損失ゼロ）。上昇継続→第2の半分を無料で保有。最悪の場合：第1の半分で少額利益、第2でゼロ。',
},
'zh': {
    's08.h1': 'TP位选择',
    's08.h2': '触及TP时的处理流程',
    's08.f1.name': '平仓一半仓位（半仓止盈）',
    's08.f1.desc': '机器人发出市价单，平仓<strong>持有总数量的恰好一半</strong>。例如：0.01 BTC → 在TP价位卖出0.005 BTC。这一半的利润被锁定。',
    's08.f2.name': 'SL移至平均成本（保本）',
    's08.f2.desc': '止损移至所有入场的加权平均成本价。若价格回落至此位，剩余一半在保本价平仓——不产生亏损。',
    's08.f3.name': '剩余一半免费持有',
    's08.f3.desc': '第二半仓没有固定TP。持续持有直至保本止损触发或下一个级别到达，捕捉超过第一个位的额外涨幅。',
    's08.callout2': '<div class="callout-label">逻辑</div>在支撑位以紧止损（3–6%）入场。价格反弹至下一阻力位→平仓一半，锁定利润。回落至平均成本→剩余部分保本平仓（零亏损）。继续上涨→第二半仓免费持有。最差情况：第一半有小额利润，第二半为零。',
},
'vi': {
    's08.h1': 'Chọn mức TP',
    's08.h2': 'Xử lý khi chạm TP',
    's08.f1.name': 'Đóng nửa kích cỡ vị thế (Đóng nửa)',
    's08.f1.desc': 'Bot đặt lệnh thị trường để đóng chính xác <strong>nửa tổng kích cỡ đang giữ</strong>. Ví dụ: 0.01 BTC → bán 0.005 BTC tại mức TP. Lợi nhuận trên nửa này được khóa.',
    's08.f2.name': 'SL dời về giá vào lệnh trung bình (Hòa vốn)',
    's08.f2.desc': 'Stop loss dời đến giá vào lệnh trung bình có trọng số của tất cả các lần vào. Nếu giá kéo về mức này, nửa còn lại đóng ở hòa vốn — không lỗ.',
    's08.f3.name': 'Nửa còn lại giữ miễn phí',
    's08.f3.desc': 'Không có TP cố định cho nửa thứ hai. Giữ mở cho đến khi SL hòa vốn chạm hoặc mức tiếp theo đạt được, nắm bắt thêm biến động vượt qua mức đầu tiên.',
    's08.callout2': '<div class="callout-label">Logic</div>Vào lệnh tại hỗ trợ với SL chặt (3–6%). Giá nảy lên kháng cự tiếp theo → đóng nửa, khóa lợi nhuận. Kéo về giá vào trung bình → đóng phần còn lại ở hòa vốn (không lỗ). Tiếp tục tăng → giữ nửa thứ hai miễn phí. Trường hợp xấu nhất: lợi nhuận nhỏ từ nửa đầu, bằng 0 ở nửa sau.',
},
'ru': {
    's08.h1': 'Выбор уровня TP',
    's08.h2': 'Действия при достижении TP',
    's08.f1.name': 'Закрытие половины позиции',
    's08.f1.desc': 'Бот размещает рыночный ордер на закрытие ровно <strong>половины от общего удерживаемого объёма</strong>. Например: 0.01 BTC → продать 0.005 BTC по цене TP. Прибыль на эту половину зафиксирована.',
    's08.f2.name': 'SL переносится на среднюю цену входа (безубыток)',
    's08.f2.desc': 'Стоп-лосс перемещается на взвешенную среднюю цену входа по всем входам. Если цена откатит к этому уровню, оставшаяся половина закроется по безубытку — без потерь.',
    's08.f3.name': 'Вторая половина ездит бесплатно',
    's08.f3.desc': 'Фиксированного TP для второй половины нет. Она остаётся открытой до срабатывания безубыточного SL или достижения следующего уровня, захватывая дополнительное движение сверх первого уровня.',
    's08.callout2': '<div class="callout-label">Логика</div>Вход на поддержке с тесным SL (3–6%). Цена отскакивает к следующему сопротивлению → закрываем половину, фиксируем прибыль. Откат к средней цене входа → закрываем остаток по безубытку (ноль потерь). Рост продолжается → вторая половина едет бесплатно. Худший случай: небольшая прибыль на первой половине, ноль на второй.',
},
'tr': {
    's08.h1': 'TP Seviyesi Seçimi',
    's08.h2': 'TP\'ye Ulaşıldığında Yapılanlar',
    's08.f1.name': 'Pozisyonun Yarısını Kapat (Yarı Kâr Al)',
    's08.f1.desc': 'Bot, <strong>tutulan toplam miktarın tam yarısını</strong> kapatmak için piyasa emri verir. Örn: 0.01 BTC → TP seviyesinde 0.005 BTC sat. Bu yarının kârı kilitlendi.',
    's08.f2.name': 'SL\'yi Ortalama Giriş Fiyatına Taşı (Başabaş)',
    's08.f2.desc': 'Zararı durdur, tüm girişlerin ağırlıklı ortalama giriş fiyatına taşınır. Fiyat bu seviyeye geri çekilirse kalan yarı başabaştan kapanır — zarar yok.',
    's08.f3.name': 'Kalan Yarı Bedavaya Biner',
    's08.f3.desc': 'İkinci yarı için sabit TP yoktur. Başabaş SL tetiklenene veya bir sonraki seviyeye ulaşılana kadar açık kalarak birinci seviyenin ötesindeki ek hareketi yakalar.',
    's08.callout2': '<div class="callout-label">Mantık</div>Destek noktasında dar SL (3–6%) ile gir. Fiyat bir sonraki dirence sıçrar → yarısını kapat, kârı kilitle. Ortalama giriş fiyatına geri çekilirse → kalan kısım başabaştan kapansın (sıfır kayıp). Yükselmeye devam ederse → ikinci yarı bedavaya biner. En kötü senaryo: birinci yarıda küçük kâr, ikincide sıfır.',
},
'es': {
    's08.h1': 'Selección del Nivel de TP',
    's08.h2': 'Qué Sucede al Alcanzar el TP',
    's08.f1.name': 'Cierre de la mitad del tamaño de posición',
    's08.f1.desc': 'El bot coloca una orden de mercado para cerrar exactamente <strong>la mitad del tamaño total mantenido</strong>. Ej: 0.01 BTC → vender 0.005 BTC en el nivel TP. La ganancia en esta mitad queda asegurada.',
    's08.f2.name': 'SL se mueve al precio de entrada promedio (Break-Even)',
    's08.f2.desc': 'El stop loss se mueve al precio de entrada ponderado de todas las entradas. Si el precio retrocede a este nivel, la mitad restante cierra en break-even — sin pérdida.',
    's08.f3.name': 'La mitad restante viaja gratis',
    's08.f3.desc': 'No hay TP fijo para la segunda mitad. Permanece abierta hasta que el SL de break-even sea tocado o se alcance el siguiente nivel, capturando cualquier movimiento adicional más allá del primer nivel.',
    's08.callout2': '<div class="callout-label">La Lógica</div>Entrada en soporte con SL ajustado (3–6%). El precio rebota hacia la siguiente resistencia → cierre de mitad, beneficio asegurado. Si retrocede al precio promedio de entrada → cierre del resto en break-even (pérdida cero). Si sigue subiendo → segunda mitad viaja gratis. Peor caso: pequeña ganancia en la primera mitad, cero en la segunda.',
},
'pt': {
    's08.h1': 'Seleção do Nível de TP',
    's08.h2': 'O Que Acontece ao Atingir o TP',
    's08.f1.name': 'Fechar metade do tamanho da posição',
    's08.f1.desc': 'O bot coloca uma ordem de mercado para fechar exatamente <strong>metade do tamanho total mantido</strong>. Ex: 0.01 BTC → vender 0.005 BTC no nível TP. O lucro nesta metade é travado.',
    's08.f2.name': 'SL move para o preço médio de entrada (Break-Even)',
    's08.f2.desc': 'O stop loss é movido para o preço médio ponderado de entrada de todas as entradas. Se o preço recuar para este nível, a metade restante fecha no break-even — sem perda.',
    's08.f3.name': 'Metade restante viaja de graça',
    's08.f3.desc': 'Não há TP fixo para a segunda metade. Permanece aberta até que o SL de break-even seja atingido ou o próximo nível seja alcançado, capturando qualquer movimento adicional além do primeiro nível.',
    's08.callout2': '<div class="callout-label">A Lógica</div>Entrada no suporte com SL ajustado (3–6%). Preço sobe para a próxima resistência → fechar metade, lucro travado. Se recuar ao preço médio de entrada → fechar o resto no break-even (perda zero). Se continuar subindo → segunda metade viaja de graça. Pior caso: pequeno lucro na primeira metade, zero na segunda.',
},
'id': {
    's08.h1': 'Pemilihan Level TP',
    's08.h2': 'Yang Terjadi Saat TP Tercapai',
    's08.f1.name': 'Tutup setengah ukuran posisi',
    's08.f1.desc': 'Bot menempatkan market order untuk menutup tepat <strong>setengah dari total ukuran yang dipegang</strong>. Misal: 0.01 BTC → jual 0.005 BTC di level TP. Keuntungan pada setengah ini dikunci.',
    's08.f2.name': 'SL Pindah ke Harga Entri Rata-rata (Break-Even)',
    's08.f2.desc': 'Stop loss dipindahkan ke harga entri rata-rata tertimbang dari semua entri. Jika harga kembali ke level ini, setengah yang tersisa ditutup di break-even — tanpa kerugian.',
    's08.f3.name': 'Setengah Sisanya Gratis',
    's08.f3.desc': 'Tidak ada TP tetap untuk setengah kedua. Tetap terbuka sampai SL break-even tersentuh atau level berikutnya tercapai, menangkap gerakan tambahan melewati level pertama.',
    's08.callout2': '<div class="callout-label">Logikanya</div>Masuk di support dengan SL ketat (3–6%). Harga naik ke resistance berikutnya → tutup setengah, kunci profit. Jika kembali ke rata-rata masuk → tutup sisanya di break-even (nol kerugian). Jika terus naik → setengah kedua gratis. Kasus terburuk: profit kecil dari setengah pertama, nol dari setengah kedua.',
},
})

# ── Update patch block in file ────────────────────────────────────────────────
patch_json = json.dumps(patch, ensure_ascii=False)
MARKER_START = '  // i18n patch: additional keys not in the main GT object\n  (function(p) {\n'
MARKER_END   = '  function captureOriginals()'
start = content.find(MARKER_START)
end   = content.find(MARKER_END, start)
assert start != -1 and end != -1

new_block = (
    '  // i18n patch: additional keys not in the main GT object\n'
    '  (function(p) {\n'
    '    for (var l in p) { if (GT[l]) { var d = p[l]; for (var k in d) GT[l][k] = d[k]; } }\n'
    f'  }}({patch_json}));\n\n'
)
content = content[:start] + new_block + content[end:]

with open('/home/user/oracletrading/ayilon/bot-guide.html', 'w', encoding='utf-8') as f:
    f.write(content)

total = sum(len(v) for v in patch.values())
print(f"Part 3 done. {len(html_attrs)} attrs, {total} translation keys across {len(patch)} languages")
