#!/usr/bin/env python3
"""Part 4d: new translations for Section 5 strategy description paragraphs (s05.d1-d10)"""
import json

new_patch = {lang: {} for lang in ['ko','ja','zh','vi','ru','tr','es','pt','id']}

d1 = {
    'ko': "사용자가 선택한 타임프레임에서 14기간 RSI가 30 이하(과매도)로 떨어지면 롱 포지션에 진입합니다. DCA 진입은 첫 진입가와 스윙로우(SL) 사이를 N등분한 지점에 배치됩니다. 익절은 진입가 위의 가장 가까운 저항 레벨을 목표로 합니다. <strong>숏 사이드(RSI ≥ 70)는 비활성화되어 있습니다</strong> — 강세장에서는 모멘텀이 70 이상에서 장기간 유지될 수 있기 때문입니다.",
    'ja': "ユーザーが選択したタイムフレームで14期間RSIが30以下（過売り）になるとロングポジションに入ります。DCAエントリーは最初のエントリー価格とスイングロー（SL）の間をN等分した位置に配置されます。テイクプロフィットはエントリーより上の最も近いレジスタンスレベルを目標とします。<strong>ショート側（RSI ≥ 70）は無効化されています</strong> — 強気市場ではモメンタムが70以上で長期間持続することがあるためです。",
    'zh': "当用户选定时间周期上的14周期RSI跌至30以下（超卖）时开多仓。DCA加仓在首次入场价与摆动低点（SL）之间等分N份的位置依次下单。止盈目标为入场价上方最近的阻力位。<strong>空头方向（RSI ≥ 70）已禁用</strong>——因为在牛市中动能可能在70以上长时间维持。",
    'vi': "Vào lệnh long khi RSI 14 kỳ trên khung thời gian người dùng chọn giảm xuống bằng hoặc dưới 30 (quá bán). Các lệnh DCA được đặt tại N điểm chia đều giữa giá vào lệnh đầu tiên và đáy swing (SL). Take profit hướng đến mức kháng cự gần nhất phía trên giá vào. <strong>Phía short (RSI ≥ 70) bị tắt</strong> — vì động lượng có thể duy trì trên 70 trong thời gian dài ở thị trường tăng.",
    'ru': "Открывает лонг, когда 14-периодный RSI на выбранном пользователем таймфрейме опускается до 30 или ниже (перепроданность). DCA-входы размещаются на N равных интервалах между ценой первого входа и минимумом свинга (SL). Тейк-профит ориентирован на ближайший уровень сопротивления выше входа. <strong>Шорт-сторона (RSI ≥ 70) отключена</strong> — на бычьих рынках моментум может удерживаться выше 70 длительное время.",
    'tr': "Kullanıcının seçtiği zaman diliminde 14 periyotluk RSI 30 veya altına (aşırı satım) düştüğünde long pozisyon açar. DCA girişleri ilk giriş fiyatı ile salınım dibi (SL) arasında N eşit aralıkta yerleştirilir. Kar al, girişin üzerindeki en yakın direnç seviyesini hedefler. <strong>Short taraf (RSI ≥ 70) devre dışıdır</strong> — boğa piyasalarında momentum 70 üzerinde uzun süre kalabilir.",
    'es': "Abre una posición larga cuando el RSI de 14 periodos en el marco temporal seleccionado cae a 30 o menos (sobreventa). Las entradas DCA se colocan en N intervalos iguales entre el precio de la primera entrada y el mínimo swing (SL). El take profit apunta al nivel de resistencia más cercano por encima de la entrada. <strong>El lado corto (RSI ≥ 70) está desactivado</strong> — el momentum puede mantenerse por encima de 70 durante periodos prolongados en mercados alcistas.",
    'pt': "Abre uma posição longa quando o RSI de 14 períodos no timeframe selecionado cai para 30 ou menos (sobrevenda). As entradas DCA são colocadas em N intervalos iguais entre o preço da primeira entrada e a mínima de swing (SL). O take profit visa o nível de resistência mais próximo acima da entrada. <strong>O lado short (RSI ≥ 70) está desativado</strong> — o momentum pode se manter acima de 70 por períodos prolongados em mercados em alta.",
    'id': "Membuka posisi long ketika RSI 14 periode pada timeframe yang dipilih pengguna turun ke 30 atau lebih rendah (oversold). Entri DCA ditempatkan pada N interval yang sama antara harga entri pertama dan swing low (SL). Take profit menargetkan level resistance terdekat di atas entri. <strong>Sisi short (RSI ≥ 70) dinonaktifkan</strong> — momentum dapat bertahan di atas 70 untuk periode yang lama di pasar bullish.",
}
d2 = {
    'ko': "6개의 이동평균선(10, 20, 50, 100, 200 SMA + 34 EMA) 중 최소 3개가 상승 정렬(가격이 선택된 모든 MA 위)이어야 합니다. 5분봉이 가장 가까운 MA까지 아래꼬리를 만들고 그 위에서 마감하면 롱에 진입합니다 — MA로의 풀백 바운스입니다. 롱 전용이며 숏 진입은 없습니다.",
    'ja': "6本の移動平均線（10, 20, 50, 100, 200 SMA + 34 EMA）のうち最低3本が上昇配列（価格が選択された全MAより上）である必要があります。5分足が最も近いMAまで下ヒゲを付け、その上で終値を付けるとロングに入ります — MAへのプルバックバウンスです。ロング専用でショートエントリーはありません。",
    'zh': "需要6条均线（10、20、50、100、200 SMA + 34 EMA）中至少3条呈多头排列（价格高于所有所选均线）。当5分钟K线下影线触及最近的均线并在其上方收盘时开多——即均线回踩反弹。仅做多，无空头入场。",
    'vi': "Yêu cầu ít nhất 3 trong 6 đường MA (10, 20, 50, 100, 200 SMA + 34 EMA) sắp xếp theo hướng tăng (giá nằm trên tất cả MA đã chọn). Vào long khi nến 5 phút có bóng dưới chạm MA gần nhất và đóng cửa trên đó — một cú bounce pullback về MA. Chỉ long; không có lệnh short.",
    'ru': "Требуется, чтобы минимум 3 из 6 скользящих средних (10, 20, 50, 100, 200 SMA + 34 EMA) были в бычьем выравнивании (цена выше всех выбранных MA). Открывает лонг, когда 5-минутная свеча опускается тенью к ближайшей MA и закрывается выше неё — отскок от MA на откате. Только лонг; шорт-входов нет.",
    'tr': "6 hareketli ortalamadan (10, 20, 50, 100, 200 SMA + 34 EMA) en az 3'ünün yükseliş hizalamasında olması gerekir (fiyat seçilen tüm MA'ların üzerinde). 5 dakikalık mum en yakın MA'ya kadar gölge yapıp üzerinde kapandığında long açar — MA'ya geri çekilme sıçraması. Sadece long; short girişi yoktur.",
    'es': "Requiere que al menos 3 de las 6 medias móviles (SMA 10, 20, 50, 100, 200 + EMA 34) estén en alineación alcista (precio por encima de todas las MA seleccionadas). Abre largo cuando la vela de 5m forma una mecha hacia abajo hasta la MA más cercana y cierra por encima de ella — un rebote de retroceso a la MA. Solo largo; sin entradas cortas.",
    'pt': "Requer que pelo menos 3 das 6 médias móveis (SMA 10, 20, 50, 100, 200 + EMA 34) estejam em alinhamento de alta (preço acima de todas as MAs selecionadas). Abre long quando a vela de 5m forma um pavio para baixo até a MA mais próxima e fecha acima dela — um repique de pullback para a MA. Somente long; sem entradas short.",
    'id': "Memerlukan setidaknya 3 dari 6 moving average (SMA 10, 20, 50, 100, 200 + EMA 34) dalam keselarasan bullish (harga di atas semua MA yang dipilih). Membuka long ketika candle 5m membentuk sumbu bawah hingga MA terdekat dan ditutup di atasnya — pantulan pullback ke MA. Hanya long; tidak ada entri short.",
}
d3 = {
    'ko': "내장된 기본 전략입니다. 스윙 고점/저점과 거래량 프로파일을 사용하여 1H/4H 캔들에서 지지 및 저항 레벨을 감지합니다. 5분 가격이 지지 레벨을 터치하며 상승 바운스 캔들이 나오면 롱에 진입합니다. 평균 이상 거래량의 하락 임펄스 캔들 이후 저항으로 50% 되돌림이 나오면 숏에 진입합니다. SL = 이전 3개 5분 캔들의 스윙로우(롱) / 스윙하이(숏).",
    'ja': "組み込みのデフォルト戦略です。スイングハイ/ローと出来高プロファイルを使用して1H/4Hローソク足からサポート・レジスタンスレベルを検出します。5分価格がサポートレベルにタッチし上昇バウンスローソク足が出るとロングに入ります。平均を上回る出来高の下落インパルスローソク足の後にレジスタンスへの50%リトレースが続くとショートに入ります。SL = 直前3本の5分ローソク足のスイングロー（ロング）/スイングハイ（ショート）。",
    'zh': "内置的默认策略。使用摆动高点/低点和成交量分布从1H/4H K线中检测支撑和阻力位。当5分钟价格触及支撑位并出现看涨反弹K线时开多。当放量看跌冲击K线后出现50%回撤至阻力位时开空。SL = 前3根5分钟K线的摆动低点（多）/摆动高点（空）。",
    'vi': "Chiến lược mặc định tích hợp. Phát hiện mức hỗ trợ và kháng cự từ nến 1H/4H bằng đỉnh/đáy swing và hồ sơ khối lượng. Vào long khi giá 5 phút chạm mức hỗ trợ với nến bounce tăng. Vào short khi nến impulse giảm với khối lượng trên trung bình theo sau bởi hồi 50% về kháng cự. SL = đáy swing (long) / đỉnh swing (short) của 3 nến 5 phút trước đó.",
    'ru': "Встроенная стратегия по умолчанию. Определяет уровни поддержки и сопротивления по свечам 1H/4H, используя свинг-максимумы/минимумы и профиль объёма. Открывает лонг, когда 5-минутная цена касается уровня поддержки с бычьей свечой отскока. Открывает шорт, когда медвежья импульсная свеча с объёмом выше среднего сменяется 50%-ным откатом к сопротивлению. SL = свинг-минимум (лонг) / свинг-максимум (шорт) предыдущих 3 пятиминутных свечей.",
    'tr': "Yerleşik varsayılan strateji. Salınım yüksekleri/dipleri ve hacim profili kullanarak 1S/4S mumlarından destek ve direnç seviyelerini tespit eder. 5 dakikalık fiyat bir destek seviyesine yükseliş sıçrama mumuyla dokunduğunda long açar. Ortalama üstü hacimli düşüş impuls mumunu dirence %50 geri çekilme takip ettiğinde short açar. SL = önceki 3 adet 5 dakikalık mumun salınım dibi (long) / salınım tepesi (short).",
    'es': "La estrategia predeterminada incorporada. Detecta niveles de soporte y resistencia a partir de velas 1H/4H usando máximos/mínimos swing y perfil de volumen. Abre largo cuando el precio de 5m toca un nivel de soporte con una vela de rebote alcista. Abre corto cuando una vela de impulso bajista con volumen superior al promedio es seguida por un retroceso del 50% hacia la resistencia. SL = mínimo swing (largo) / máximo swing (corto) de las 3 velas de 5m precedentes.",
    'pt': "A estratégia padrão integrada. Detecta níveis de suporte e resistência a partir de velas 1H/4H usando máximas/mínimas de swing e perfil de volume. Abre long quando o preço de 5m toca um nível de suporte com uma vela de repique de alta. Abre short quando uma vela de impulso de baixa com volume acima da média é seguida por um retrocesso de 50% até a resistência. SL = mínima de swing (long) / máxima de swing (short) das 3 velas de 5m anteriores.",
    'id': "Strategi default bawaan. Mendeteksi level support dan resistance dari candle 1H/4H menggunakan swing high/low dan profil volume. Membuka long ketika harga 5m menyentuh level support dengan candle pantulan bullish. Membuka short ketika candle impuls bearish dengan volume di atas rata-rata diikuti retracement 50% ke resistance. SL = swing low (long) / swing high (short) dari 3 candle 5m sebelumnya.",
}
d4 = {
    'ko': "롱: 10 EMA가 34 EMA를 상향 돌파(골든크로스)하고 신호 캔들에서 RSI ≥ 65. 숏: 10 EMA가 34 EMA를 하향 돌파(데드크로스)하고 RSI ≤ 35. DCA 진입은 신호 캔들 가격과 5분 차트 이전 3개 캔들의 스윙로우/하이 사이에 배치됩니다. <strong>참고:</strong> RSI 조건은 크로스오버를 마감하는 캔들에서 확인됩니다 — RSI가 아직 임계값에 도달하지 않았다면 봇은 다음 캔들에서 확인을 기다립니다.",
    'ja': "ロング：10 EMAが34 EMAを上抜け（ゴールデンクロス）し、シグナルローソク足でRSI ≥ 65。ショート：10 EMAが34 EMAを下抜け（デッドクロス）しRSI ≤ 35。DCAエントリーはシグナルローソク足の価格と5分チャートの直前3本のスイングロー/ハイの間に配置されます。<strong>注：</strong>RSI条件はクロスオーバーを終値で確定するローソク足でチェックされます — RSIがまだ閾値に達していない場合、ボットは次のローソク足での確認を待ちます。",
    'zh': "多头：10 EMA上穿34 EMA（黄金交叉）且信号K线RSI ≥ 65。空头：10 EMA下穿34 EMA（死亡交叉）且RSI ≤ 35。DCA加仓位于信号K线价格与5分钟图前3根K线摆动低/高点之间。<strong>注意：</strong>RSI条件在确认交叉的K线收盘时检查——若RSI尚未达到阈值，机器人会等待下一根K线确认。",
    'vi': "Long: 10 EMA cắt lên trên 34 EMA (golden cross) VÀ RSI ≥ 65 tại nến tín hiệu. Short: 10 EMA cắt xuống dưới 34 EMA (death cross) VÀ RSI ≤ 35. Các lệnh DCA được đặt giữa giá nến tín hiệu và đỉnh/đáy swing của 3 nến trước đó trên khung 5 phút. <strong>Lưu ý:</strong> điều kiện RSI được kiểm tra tại nến đóng xác nhận crossover — nếu RSI chưa đạt ngưỡng, bot sẽ chờ xác nhận ở nến tiếp theo.",
    'ru': "Лонг: 10 EMA пересекает 34 EMA снизу вверх (золотой крест) И RSI ≥ 65 на сигнальной свече. Шорт: 10 EMA пересекает 34 EMA сверху вниз (мёртвый крест) И RSI ≤ 35. DCA-входы располагаются между ценой сигнальной свечи и свинг-минимумом/максимумом предыдущих 3 свечей на 5-минутном графике. <strong>Примечание:</strong> условие RSI проверяется на свече, закрывающей пересечение — если RSI ещё не достиг порога, бот ждёт подтверждения на следующей свече.",
    'tr': "Long: 10 EMA, 34 EMA'yı yukarı keser (altın kesişim) VE sinyal mumunda RSI ≥ 65. Short: 10 EMA, 34 EMA'yı aşağı keser (ölüm kesişimi) VE RSI ≤ 35. DCA girişleri, sinyal mum fiyatı ile 5 dakikalık grafikte önceki 3 mumun salınım dibi/tepesi arasına yerleştirilir. <strong>Not:</strong> RSI koşulu, kesişimi kapatan mumda kontrol edilir — RSI henüz eşiğe ulaşmadıysa bot bir sonraki mumda onay bekler.",
    'es': "Largo: la EMA de 10 cruza por encima de la EMA de 34 (cruce dorado) Y RSI ≥ 65 en la vela de señal. Corto: la EMA de 10 cruza por debajo de la EMA de 34 (cruce de la muerte) Y RSI ≤ 35. Las entradas DCA se espacian entre el precio de la vela de señal y el mínimo/máximo swing de las 3 velas anteriores en el gráfico de 5m. <strong>Nota:</strong> la condición RSI se verifica en la vela que cierra el cruce — si el RSI aún no ha alcanzado el umbral, el bot espera confirmación en la siguiente vela.",
    'pt': "Long: a EMA de 10 cruza acima da EMA de 34 (cruz dourada) E RSI ≥ 65 na vela de sinal. Short: a EMA de 10 cruza abaixo da EMA de 34 (cruz da morte) E RSI ≤ 35. As entradas DCA são espaçadas entre o preço da vela de sinal e a mínima/máxima de swing das 3 velas anteriores no gráfico de 5m. <strong>Nota:</strong> a condição RSI é verificada na vela que fecha o cruzamento — se o RSI ainda não atingiu o limite, o bot espera confirmação na próxima vela.",
    'id': "Long: EMA 10 melintasi di atas EMA 34 (golden cross) DAN RSI ≥ 65 pada candle sinyal. Short: EMA 10 melintasi di bawah EMA 34 (death cross) DAN RSI ≤ 35. Entri DCA diberi jarak antara harga candle sinyal dan swing low/high dari 3 candle sebelumnya pada chart 5m. <strong>Catatan:</strong> kondisi RSI diperiksa pada candle yang menutup crossover — jika RSI belum mencapai ambang batas, bot menunggu konfirmasi pada candle berikutnya.",
}
d5 = {
    'ko': "20기간 BB(표준편차 2)를 사용합니다. 5분 캔들이 하단 밴드 아래에서 마감하고 다음 캔들이 밴드 안으로 다시 마감하면(재진입 확인) 롱에 진입합니다. 상단 밴드에서 반대 조건일 때 숏에 진입합니다. 트렌드 필터: 일봉 트렌드가 강하게 하락세(가격이 200 SMA 아래)일 때는 롱 진입을 건너뜁니다.",
    'ja': "20期間BB（標準偏差2）を使用します。5分ローソク足が下限バンドの下で終値を付け、次のローソク足がバンド内に戻って終値を付けると（再エントリー確認）ロングに入ります。上限バンドでの逆条件でショートに入ります。トレンドフィルター：日次トレンドが強く下降している（価格が200 SMAより下）場合、ロングエントリーはスキップされます。",
    'zh': "使用20周期布林带（2个标准差）。当5分钟K线收于下轨之下，且下一根K线收回带内（重新进入确认）时开多。在上轨出现镜像条件时开空。趋势过滤：当日线趋势强烈看跌（价格低于200 SMA）时跳过开多。",
    'vi': "Sử dụng BB 20 kỳ với 2 độ lệch chuẩn. Vào long khi nến 5 phút đóng dưới dải dưới và nến tiếp theo đóng trở lại trong dải (xác nhận tái nhập). Vào short ở điều kiện đối xứng tại dải trên. Bộ lọc xu hướng: bỏ qua lệnh long khi xu hướng ngày mạnh giảm (giá dưới 200 SMA).",
    'ru': "Использует 20-периодные BB с 2 стандартными отклонениями. Открывает лонг, когда 5-минутная свеча закрывается ниже нижней полосы, а следующая свеча закрывается обратно внутри полосы (подтверждение повторного входа). Открывает шорт при зеркальном условии на верхней полосе. Фильтр тренда: лонг-входы пропускаются, когда дневной тренд сильно медвежий (цена ниже 200 SMA).",
    'tr': "2 standart sapmalı 20 periyotluk BB kullanır. 5 dakikalık mum alt bandın altında kapandığında ve sonraki mum bandın içine geri kapandığında (yeniden giriş onayı) long açar. Üst bantta ayna koşulda short açar. Trend filtresi: günlük trend güçlü düşüşteyken (fiyat 200 SMA altında) long girişleri atlanır.",
    'es': "Usa BB de 20 periodos con 2 desviaciones estándar. Abre largo cuando la vela de 5m cierra por debajo de la banda inferior y la siguiente vela cierra de vuelta dentro de la banda (confirmación de reentrada). Abre corto en la condición simétrica en la banda superior. Filtro de tendencia: las entradas largas se omiten cuando la tendencia diaria es fuertemente bajista (precio por debajo de la SMA de 200).",
    'pt': "Usa BB de 20 períodos com 2 desvios padrão. Abre long quando a vela de 5m fecha abaixo da banda inferior e a próxima vela fecha de volta dentro da banda (confirmação de reentrada). Abre short na condição espelhada na banda superior. Filtro de tendência: entradas long são ignoradas quando a tendência diária está fortemente em baixa (preço abaixo da SMA de 200).",
    'id': "Menggunakan BB 20 periode dengan 2 standar deviasi. Membuka long ketika candle 5m ditutup di bawah band bawah dan candle berikutnya ditutup kembali di dalam band (konfirmasi re-entry). Membuka short pada kondisi cermin di band atas. Filter tren: entri long dilewati ketika tren harian sangat bearish (harga di bawah SMA 200).",
}
d6 = {
    'ko': "1H 차트에서 20기간 저항 레벨을 식별합니다. 5분 캔들이 거래량이 20기간 평균 거래량의 2배 이상으로 이 레벨 위에서 마감하면 롱에 진입합니다. 돌파된 저항선이 첫 DCA 기준가가 됩니다. SL = 돌파 캔들의 저가. 롱 위주이며, 추가 RSI 필터와 함께 프리미엄에서 숏 브레이크다운도 가능합니다.",
    'ja': "1Hチャートで20期間レジスタンスレベルを特定します。5分ローソク足が20期間平均出来高の2倍以上の出来高でこのレベルより上で終値を付けるとロングに入ります。突破されたレジスタンスが最初のDCA基準価格になります。SL = ブレイクアウトバーのローソク足安値。ロング志向で、追加のRSIフィルターを使えばプレミアムでショートブレイクダウンも利用可能です。",
    'zh': "在1H图上识别20周期阻力位。当5分钟K线以≥20周期平均成交量2倍的量收于该位之上时开多。被突破的阻力位成为首个DCA参考价。SL = 突破棒的K线低点。偏多头；高级版中配合额外RSI过滤器可用于空头破位。",
    'vi': "Xác định mức kháng cự 20 kỳ trên khung 1H. Vào long khi nến 5 phút đóng trên mức này với khối lượng ≥ 2× khối lượng trung bình 20 kỳ. Kháng cự bị phá vỡ trở thành giá tham chiếu DCA đầu tiên. SL = đáy nến của thanh breakout. Ưu tiên long; breakdown short có sẵn ở gói Premium với bộ lọc RSI bổ sung.",
    'ru': "Определяет 20-периодный уровень сопротивления на графике 1H. Открывает лонг, когда 5-минутная свеча закрывается выше этого уровня с объёмом ≥ 2× среднего объёма за 20 периодов. Пробитое сопротивление становится первой ценой ориентира DCA. SL = минимум свечи прорыва. Уклон в сторону лонга; шорт-пробои доступны в Premium с дополнительным RSI-фильтром.",
    'tr': "1S grafiğinde 20 periyotluk direnç seviyesini belirler. 5 dakikalık mum, 20 periyot ortalama hacmin 2 katı veya daha fazla hacimle bu seviyenin üzerinde kapandığında long açar. Kırılan direnç ilk DCA referans fiyatı olur. SL = breakout barının mum dibi. Long ağırlıklı; ek RSI filtresiyle Premium'da short kırılımlar da mevcuttur.",
    'es': "Identifica el nivel de resistencia de 20 periodos en el gráfico de 1H. Abre largo cuando una vela de 5m cierra por encima de este nivel con volumen ≥ 2× el volumen promedio de 20 periodos. La resistencia rota se convierte en el primer precio de referencia DCA. SL = mínimo de la vela de ruptura. Sesgo largo; rupturas cortas disponibles en Premium con un filtro RSI adicional.",
    'pt': "Identifica o nível de resistência de 20 períodos no gráfico de 1H. Abre long quando uma vela de 5m fecha acima deste nível com volume ≥ 2× o volume médio de 20 períodos. A resistência rompida se torna o primeiro preço de referência DCA. SL = mínima da vela de rompimento. Tendência long; rompimentos short disponíveis no Premium com um filtro RSI adicional.",
    'id': "Mengidentifikasi level resistance 20 periode pada chart 1H. Membuka long ketika candle 5m ditutup di atas level ini dengan volume ≥ 2× volume rata-rata 20 periode. Resistance yang ditembus menjadi harga referensi DCA pertama. SL = low candle dari bar breakout. Cenderung long; breakdown short tersedia di Premium dengan filter RSI tambahan.",
}
d7 = {
    'ko': "6개의 MA(10, 20, 34, 50, 100, 200)가 완전한 상승 정렬(각 MA가 더 긴 MA 위)이어야 합니다. 가격이 리본에서 가장 짧은 MA(10)를 터치하고 5분 차트의 마지막 3개 캔들이 풀백을 보이면 롱에 진입합니다. 이 전략은 확인된 강한 상승 트렌드에서만 발동합니다. 롱 전용입니다.",
    'ja': "6本のMA（10, 20, 34, 50, 100, 200）が完全な上昇配列（各MAがより長いMAより上）である必要があります。価格がリボン内の最短MA（10）にタッチし、5分足の直近3本がプルバックを示すとロングに入ります。この戦略は確認された強い上昇トレンドでのみ発動します。ロング専用です。",
    'zh': "需要6条均线（10、20、34、50、100、200）呈完全多头排列（每条均线高于更长周期的均线）。当价格触及均线带中最短均线（10）且5分钟图最近3根K线显示回调时开多。该策略仅在确认的强劲上升趋势中触发。仅做多。",
    'vi': "Yêu cầu 6 đường MA (10, 20, 34, 50, 100, 200) sắp xếp hoàn toàn theo hướng tăng (mỗi MA nằm trên MA dài hơn tiếp theo). Vào long khi giá chạm MA ngắn nhất (10) trong ribbon và 3 nến cuối trên khung 5 phút cho thấy pullback. Chiến lược này chỉ kích hoạt trong xu hướng tăng mạnh đã xác nhận. Chỉ long.",
    'ru': "Требует, чтобы 6 MA (10, 20, 34, 50, 100, 200) были в полном бычьем выравнивании (каждая MA выше следующей более длинной). Открывает лонг, когда цена касается самой короткой MA (10) в ленте, а последние 3 свечи на 5-минутке показывают откат. Стратегия срабатывает только в подтверждённых сильных восходящих трендах. Только лонг.",
    'tr': "6 MA'nın (10, 20, 34, 50, 100, 200) tam yükseliş hizalamasında olmasını gerektirir (her MA bir sonraki daha uzun MA'nın üzerinde). Fiyat banttaki en kısa MA'ya (10) dokunduğunda ve 5 dakikalık grafikte son 3 mum geri çekilme gösterdiğinde long açar. Bu strateji yalnızca onaylanmış güçlü yükseliş trendlerinde tetiklenir. Sadece long.",
    'es': "Requiere que 6 MAs (10, 20, 34, 50, 100, 200) estén en alineación alcista completa (cada MA por encima de la siguiente más larga). Abre largo cuando el precio toca la MA más corta (10) de la cinta y las últimas 3 velas en 5m muestran un retroceso. Esta estrategia solo se activa en tendencias alcistas fuertes confirmadas. Solo largo.",
    'pt': "Requer que 6 MAs (10, 20, 34, 50, 100, 200) estejam em alinhamento de alta total (cada MA acima da próxima mais longa). Abre long quando o preço toca a MA mais curta (10) na faixa e as últimas 3 velas em 5m mostram um pullback. Esta estratégia só dispara em tendências de alta fortes confirmadas. Somente long.",
    'id': "Memerlukan 6 MA (10, 20, 34, 50, 100, 200) dalam keselarasan bullish penuh (setiap MA di atas MA yang lebih panjang berikutnya). Membuka long ketika harga menyentuh MA terpendek (10) dalam ribbon dan 3 candle terakhir pada 5m menunjukkan pullback. Strategi ini hanya aktif pada tren naik kuat yang terkonfirmasi. Hanya long.",
}
d8 = {
    'ko': "롱 진입을 위해 강세 다이버전스(가격은 낮은 저점, MACD 히스토그램은 높은 저점)를 감지하고, 숏을 위해 약세 다이버전스를 감지합니다. 다이버전스는 사용자가 선택한 타임프레임의 마지막 10개 캔들에서 확인됩니다. 강한 트렌드 시장에서의 다이버전스 거래를 피하기 위해 RSI 필터(롱은 RSI > 40, 숏은 RSI < 60)가 필요합니다.",
    'ja': "ロングエントリーのために強気ダイバージェンス（価格はより低い安値、MACDヒストグラムはより高い安値）を検出し、ショートのために弱気ダイバージェンスを検出します。ダイバージェンスはユーザーが選択したタイムフレームの直近10本のローソク足で確認されます。強いトレンド市場でのダイバージェンス取引を避けるため、RSIフィルター（ロングはRSI > 40、ショートはRSI < 60）が必要です。",
    'zh': "检测看涨背离（价格创新低，MACD柱状图未创新低）用于多头入场，检测看跌背离用于空头。背离在用户选定时间周期的最近10根K线内确认。需要RSI过滤器（多头RSI > 40，空头RSI < 60）以避免在强趋势市场中进行背离交易。",
    'vi': "Phát hiện phân kỳ tăng (giá tạo đáy thấp hơn, histogram MACD tạo đáy cao hơn) cho lệnh long, và phân kỳ giảm cho lệnh short. Phân kỳ được xác nhận trong 10 nến gần nhất trên khung thời gian người dùng chọn. Cần bộ lọc RSI (RSI > 40 cho long, RSI < 60 cho short) để tránh giao dịch phân kỳ trong thị trường có xu hướng mạnh.",
    'ru': "Определяет бычью дивергенцию (цена делает более низкий минимум, гистограмма MACD делает более высокий минимум) для лонг-входов и медвежью дивергенцию для шортов. Дивергенция подтверждается на последних 10 свечах выбранного таймфрейма. Требуется RSI-фильтр (RSI > 40 для лонгов, RSI < 60 для шортов), чтобы избежать дивергентных сделок на сильно трендовых рынках.",
    'tr': "Long girişleri için boğa uyumsuzluğunu (fiyat daha düşük dip yapar, MACD histogramı daha yüksek dip yapar) ve short için ayı uyumsuzluğunu tespit eder. Uyumsuzluk, kullanıcının seçtiği zaman diliminde son 10 mumda onaylanır. Güçlü trend piyasalarda uyumsuzluk işlemlerinden kaçınmak için RSI filtresi gerekir (long için RSI > 40, short için RSI < 60).",
    'es': "Detecta divergencia alcista (el precio hace un mínimo más bajo, el histograma MACD hace un mínimo más alto) para entradas largas, y divergencia bajista para cortas. La divergencia se confirma en las últimas 10 velas del marco temporal seleccionado. Requiere un filtro RSI (RSI > 40 para largos, RSI < 60 para cortos) para evitar operaciones de divergencia en mercados con tendencia fuerte.",
    'pt': "Detecta divergência de alta (o preço faz uma mínima mais baixa, o histograma MACD faz uma mínima mais alta) para entradas long, e divergência de baixa para shorts. A divergência é confirmada nas últimas 10 velas do timeframe selecionado. Requer um filtro RSI (RSI > 40 para longs, RSI < 60 para shorts) para evitar operações de divergência em mercados fortemente em tendência.",
    'id': "Mendeteksi divergensi bullish (harga membuat low lebih rendah, histogram MACD membuat low lebih tinggi) untuk entri long, dan divergensi bearish untuk short. Divergensi dikonfirmasi selama 10 candle terakhir pada timeframe yang dipilih pengguna. Memerlukan filter RSI (RSI > 40 untuk long, RSI < 60 untuk short) untuk menghindari trading divergensi di pasar yang sedang tren kuat.",
}
d9 = {
    'ko': "무기한 스왑 펀딩비율은 시장 심리를 보여줍니다. 펀딩비율이 8시간당 +0.10%를 초과하면(시장이 심하게 롱) 봇은 숏 진입으로 군중에 반대로 베팅합니다. -0.05% 이하로 떨어지면(심하게 숏) 롱에 진입합니다. 이 전략은 펀딩 간격마다 한 번씩 확인되며 5분 신호 감지를 사용하지 않습니다.",
    'ja': "無期限スワップのファンディングレートは市場心理を反映します。ファンディングレートが8時間当たり+0.10%を超えると（市場が過度にロング）、ボットはショートエントリーで群衆に逆らいます。-0.05%を下回ると（過度にショート）、ロングに入ります。この戦略はファンディング間隔ごとに1回チェックされ、5分シグナル検出は使用しません。",
    'zh': "永续合约资金费率揭示市场情绪。当资金费率超过每8小时+0.10%（市场严重偏多）时，机器人通过开空与大众反向操作。当低于-0.05%（严重偏空）时开多。此策略每个资金费率周期检查一次，不使用5分钟信号检测。",
    'vi': "Tỷ lệ funding của hợp đồng vĩnh cửu phản ánh tâm lý thị trường. Khi tỷ lệ funding vượt +0.10% mỗi 8 giờ (thị trường quá long), bot đi ngược đám đông bằng lệnh short. Khi giảm dưới -0.05% (quá short), bot vào long. Chiến lược này được kiểm tra một lần mỗi kỳ funding và không dùng phát hiện tín hiệu 5 phút.",
    'ru': "Ставки финансирования перпетуальных свопов отражают настроение рынка. Когда ставка финансирования превышает +0.10% за 8 часов (рынок сильно перекуплен в лонг), бот открывает шорт против толпы. Когда она опускается ниже −0.05% (сильно перепродан в шорт), открывает лонг. Эта стратегия проверяется один раз за интервал финансирования и не использует 5-минутное обнаружение сигналов.",
    'tr': "Sürekli swap fonlama oranları piyasa duyarlılığını ortaya koyar. Fonlama oranı 8 saatte +%0.10'u aştığında (piyasa ağırlıklı long), bot short girişiyle kalabalığa karşı pozisyon alır. -%0.05'in altına düştüğünde (ağırlıklı short), long açar. Bu strateji her fonlama aralığında bir kez kontrol edilir ve 5 dakikalık sinyal tespiti kullanmaz.",
    'es': "Las tasas de financiamiento de swaps perpetuos revelan el sentimiento del mercado. Cuando la tasa de financiamiento supera +0.10% por 8h (el mercado está muy largo), el bot va contra la multitud con una entrada corta. Cuando cae por debajo de −0.05% (muy corto), entra largo. Esta estrategia se verifica una vez por intervalo de financiamiento y no usa detección de señales de 5m.",
    'pt': "As taxas de financiamento de swaps perpétuos revelam o sentimento do mercado. Quando a taxa de financiamento excede +0.10% por 8h (o mercado está fortemente long), o bot vai contra a multidão com uma entrada short. Quando cai abaixo de −0.05% (fortemente short), entra long. Esta estratégia é verificada uma vez por intervalo de financiamento e não usa detecção de sinal de 5m.",
    'id': "Funding rate perpetual swap mengungkap sentimen pasar. Ketika funding rate melebihi +0.10% per 8 jam (pasar sangat long), bot melawan arus dengan entri short. Ketika turun di bawah −0.05% (sangat short), bot membuka long. Strategi ini diperiksa sekali per interval funding dan tidak menggunakan deteksi sinyal 5m.",
}
d10 = {
    'ko': "1H 차트에서 ADX > 25(강한 트렌드 확인)이고 가격이 상승 트렌드(50 SMA 위)에 있어야 합니다. 가격이 최근 고점에서 정확히 1 ATR만큼 되돌리고 회복을 시작하면 롱에 진입합니다. SL = 진입가 - 1.5 ATR. 롱 위주이며, 숏 진입은 ADX > 30 및 가격이 50 SMA 아래일 때 필요합니다.",
    'ja': "1HチャートでADX > 25（強いトレンドが確認）かつ価格が上昇トレンド（50 SMAより上）にある必要があります。価格が直近高値からちょうど1 ATR分戻り、回復を始めるとロングに入ります。SL = エントリー - 1.5 ATR。ロング志向で、ショートエントリーにはADX > 30かつ価格が50 SMAより下である必要があります。",
    'zh': "需要1H图上ADX > 25（确认强趋势）且价格处于上升趋势（高于50 SMA）。当价格从近期高点恰好回撤1个ATR并开始反弹时开多。SL = 入场价减1.5 ATR。偏多头；空头入场要求ADX > 30且价格低于50 SMA。",
    'vi': "Yêu cầu ADX > 25 (xác nhận xu hướng mạnh) trên khung 1H và giá đang trong xu hướng tăng (trên 50 SMA). Vào long khi giá hồi đúng 1 ATR từ đỉnh gần nhất và bắt đầu hồi phục. SL = giá vào trừ 1.5 ATR. Ưu tiên long; lệnh short yêu cầu ADX > 30 và giá dưới 50 SMA.",
    'ru': "Требует ADX > 25 (подтверждён сильный тренд) на графике 1H, и цена должна быть в восходящем тренде (выше 50 SMA). Открывает лонг, когда цена откатывается ровно на 1 ATR от недавнего максимума и начинает восстанавливаться. SL = вход минус 1.5 ATR. Уклон в сторону лонга; шорт-входы требуют ADX > 30 и цены ниже 50 SMA.",
    'tr': "1S grafiğinde ADX > 25 (güçlü trend onaylanmış) ve fiyatın yükseliş trendinde (50 SMA üzerinde) olmasını gerektirir. Fiyat son tepeden tam olarak 1 ATR geri çekilip toparlanmaya başladığında long açar. SL = giriş eksi 1.5 ATR. Long ağırlıklı; short girişleri ADX > 30 ve fiyatın 50 SMA altında olmasını gerektirir.",
    'es': "Requiere ADX > 25 (tendencia fuerte confirmada) en el gráfico de 1H y que el precio esté en tendencia alcista (por encima de la SMA de 50). Abre largo cuando el precio retrocede exactamente 1 ATR desde el máximo reciente y comienza a recuperarse. SL = entrada menos 1.5 ATR. Sesgo largo; las entradas cortas requieren ADX > 30 y precio por debajo de la SMA de 50.",
    'pt': "Requer ADX > 25 (tendência forte confirmada) no gráfico de 1H e o preço estar em tendência de alta (acima da SMA de 50). Abre long quando o preço recua exatamente 1 ATR da máxima recente e começa a se recuperar. SL = entrada menos 1.5 ATR. Tendência long; entradas short requerem ADX > 30 e preço abaixo da SMA de 50.",
    'id': "Memerlukan ADX > 25 (tren kuat terkonfirmasi) pada chart 1H dan harga dalam tren naik (di atas SMA 50). Membuka long ketika harga pullback tepat 1 ATR dari high terbaru dan mulai pulih. SL = entri dikurangi 1.5 ATR. Cenderung long; entri short memerlukan ADX > 30 dan harga di bawah SMA 50.",
}

DS = [d1, d2, d3, d4, d5, d6, d7, d8, d9, d10]
for lang in new_patch:
    for i, d in enumerate(DS, 1):
        new_patch[lang][f's05.d{i}'] = d[lang]

with open('/home/user/oracletrading/_p4_part3.json', 'w', encoding='utf-8') as f:
    json.dump(new_patch, f, ensure_ascii=False)
print(f"s05.d1-10 keys per lang: {len(new_patch['ko'])}")
